*** This file generated on Fri Nov 17 22:55:12 1989
*** $Id: mathieeedoubbas_lib.i,v 37.1 91/01/21 12:02:41 mks Exp $
	FUNCDEF	IEEEDPFix
	FUNCDEF	IEEEDPFlt
	FUNCDEF	IEEEDPCmp
	FUNCDEF	IEEEDPTst
	FUNCDEF	IEEEDPAbs
	FUNCDEF	IEEEDPNeg
	FUNCDEF	IEEEDPAdd
	FUNCDEF	IEEEDPSub
	FUNCDEF	IEEEDPMul
	FUNCDEF	IEEEDPDiv
	FUNCDEF	IEEEDPFloor
	FUNCDEF	IEEEDPCeil
