;Standard external references:

extrn	recal_reqd:byte
extrn	motor_on:byte
extrn	motor_timout:byte
extrn	dsk_opn_status:byte
extrn	fdc_results:byte
extrn	hf_cntrl:byte
extrn	drv_0_media:byte
extrn	drv_1_media:byte
extrn	drv_0_op:byte
extrn	drv_1_op:byte
extrn	drv_0_cyl:byte
extrn	drv_1_cyl:byte
extrn	data_rate:byte
extrn	dsk_parm_ptr:dword
extrn 	save_all:near
extrn 	restore_all:near
extrn 	nop_proc:near
extrn	read_cmos:near
extrn	write_cmos:near
extrn	chk_cmos_good:near
extrn	set_data:near
extrn	delay:near
