CC	= cl
CF	= /AL /c /FoOBJ\ /Otil /Za /Zi
AS	= masm
ASF     =  /ZI
LN  	= link
LF	= /CO

OBJ\ex6.obj : ex6.c
	$(CC) $(CF) ex6.c

ex6.exe : OBJ\ex6.obj
	$(LN) $(LF) OBJ\ex6, ,NUL.MAP , ljanus ;

