##########################################################################

MAKEFILE=	Makefile
MAKEMETA=	/usr/commodore/amiga/V37/tools/makemeta
SRCDIRPATH=	workbench/fonts/courier
SRCDIR=		11
SUBSYSNAME=	11
DISKPATH=	fonts/courier/11

AFILES=		11.asm
OFILES=		11.obj

all:		${SUBSYSNAME}.ld

.INCLUDE=${MAKEMETA}
SYMBOLOPT=
