#! /bin/csh
#
#	mergebranch [-p] <files>
#
set print=0

if (($#argv > 0) && ("$1" == "-p")) then
    set print=1
    shift
endif

if ($#argv < 1) then
    echo "Usage: $0 [-p] <files>"
    exit 1
endif

foreach i ($argv[1-])
	set head=`rlog -h $i | awk '$1 == "head:" { print int($2); exit }' - `
	if ($print == 0) then
		co -j$head $i
		rcs -u $i
		rcs -l$head $i
	else
		co -p -j$head $i
	endif
end

exit 0
