#! /bin/csh -f
#
#	CleanLib <sfd_name> ...
#
#	clean the directories associated with the _lib.sfd name(s)
#
set nonomatch
if( $#argv > 0 ) then
    foreach sfdname ( $argv[1-] )
	set dirname=`basename $sfdname:r _lib`
	rm -f RAM/$dirname/* RAM/$dirname.*
	rm -f ROM/$dirname/* ROM/$dirname.*
	rm -f LVO/$sfdname:r.obj
    end
endif
