SUBSYSNAME       = Disk
AFILES           = diskinformation.asm fileio.asm makelist.asm sizedisklist.asm setdiskprotection.asm
OTHERFILES       = makefile
OTHERFILES_NORCS = dependencies

.include /makefile_master
