/* RMake (h/protos.h) Private Prototype generation (Version 4.2)
** RMake Copyright © 1990-92 Mitchell/Ware Systems, Inc.
** RMake All Rights Reserved.
**
** This and other files GENERATED by the RMAKE system
** are the sole property of the non-commercial user; however the RMAKE
** System is the sole property of Mitchell/Ware Systems and
** available only for non-commercial use. Commercial versions of
** RMAKE can be obtained by contacting Mitchell/Ware Systems
** at (215)524-9100 or 'f.mitchell' on BIX.
*/


