CC	= cl
CF	= /AL /c /FoOBJ\ /Otil /Za /Zi
AS	= masm
ASF     =  /ZI
LN  	= link
LF	= /CO

OBJ\ex8.obj : ex8.c
	$(CC) $(CF) ex8.c

ex8.exe : OBJ\ex8.obj
	$(LN) $(LF) OBJ\ex8, ,NUL.MAP , ljanus ;

