#include	"ecc.h"
#include	<stdio.h>
/* definition of all globals variables */
/* GF 	Log, Exp etc. declared in gfmath.h */


GF	Hp[P_RANK][P_LEN] = {	/* generated by Matbuild program */
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 2, 4, 8, 16, 32, 3, 6, 12, 24, 48, 35, 5, 10, 20, 40, 19, 38, 15, 30, 60, 59, 53, 41,
1, 4, 16, 3, 12, 48, 5, 20, 19, 15, 60, 53, 17, 7, 28, 51, 9, 36, 22, 27, 47, 58, 45, 50,
1, 8, 3, 24, 5, 40, 15, 59, 17, 14, 51, 18, 22, 54, 58, 25, 13, 43, 23, 62, 57, 1, 8, 3,
};

/* GF Hq[Q_RANK][Q_LEN]; not allocated */

static	GF	Rec[P_LEN];	/* just for testing */

static	int	VecIdentical(GF *v1, GF *v2)
{
	int	i;
	for(i=0;i<P_LEN;i++)
	 {
	 	if (v1[i] != v2[i])
	 	  return FALSE;
	 }
	return TRUE;
}

static	void	CheckDecodeSingleErrors(GF *Rec)
{
	GF	Rec0[P_LEN];
	int	i,err;

	printf("\n--- SINGLE ERRORS --- ");
	for(i=0;i<P_LEN;i++)
		Rec0[i] = Rec[i];

	for(i=0;i<P_LEN;i++)
	 {
	   for(err=0;err<64;err++)
	    {
		Rec[i] = err;
		DecodeRS(Rec);

		if (VecIdentical(Rec,Rec0))
		  printf("\n*** Identical ***: pos=%d, err=%d",i,err);
		else
		  printf("\n*** ERROR ***: pos=%d, err=%d",i,err);
	    }
	 }
}

static	void	CheckDecodeDoubleErrors(GF *Rec)
{	/* ONLY checking certain combinations */

	GF	Rec0[P_LEN];
	int	i,j,err;

	printf("\n--- Double ERRORS --- ");

	for(i=0;i<P_LEN;i++)
		Rec0[i] = Rec[i];

	for(i=0;i<P_LEN;i++)
	 {
	   for(j=0;j<P_LEN;j+=2)
	    {
	       for(err=0;err<64;err+=3)
	    	{
			Rec[i] = err;
			Rec[j] = (~err & 63);	/* just some other error */
			DecodeRS(Rec);

			if (VecIdentical(Rec,Rec0))
			  printf("\n*** Identical ***: pos1=%d, err1=%d, pos2=%d, err2=%d",i,err,j,(int)Rec[j]);
			else
			  printf("\n*** ERROR ***: pos=%d, err=%d, pos2=%d, err2=%d",i,err,j,(int)Rec[j]);
		}
	       Rec[j] = 0;
	    }
	  Rec[i] = 0;
	 }
}

static	void	Check_Syndrome2()
{
	int	i;
	for(i=0;i<P_LEN;i++)
		Rec[i] = 0;

	CheckDecodeSingleErrors(Rec);

#if 1
	for(i=0;i<P_LEN;i++)
		Rec[i] = 0;
	CheckDecodeDoubleErrors(Rec);
#endif
}

static	void	RealRec(GF *Rec)
{
	int i;
	for(i=0;i<P_LEN;i++)
	 Rec[i] = 0;
#if 1
	Rec[0] = 0x9;
	Rec[1] = 0x1;
	Rec[2] = 0x3c;
	Rec[3] = 0x34;
	Rec[20] = 0xd;
	Rec[21] = 0x7;
	Rec[22] = 0x2a;
	Rec[23] = 0x20;
#else
	Rec[23] = 0x9;
	Rec[22] = 0x1;
	Rec[21] = 0x3c;
	Rec[20] = 0x34;
	Rec[3] = 0xd;
	Rec[2] = 0x7;
	Rec[1] = 0x2a;
	Rec[0] = 0x20;
#endif
}
static void	Check_Syndrome()
{
	int	i;
	for(i=0;i<P_LEN;i++)
	 Rec[i] = 0;

#if 0
	DecodeRS(Rec);

	Rec[0] = 1;
	DecodeRS(Rec);

	Rec[0] = 1; Rec[1] = 1;
	DecodeRS(Rec);

	Rec[1] = 0; Rec[23] = 1;
	DecodeRS(Rec);
#endif

#if 0
	Rec[0] = 1;
	Rec[2] = 0; Rec[23] = 0; Rec[1] = 2;
	DecodeRS(Rec);

	for(i=0;i<P_LEN;i++)
	 Rec[i] = 0;

	Rec[10] = 5; Rec[20] = 33;
	DecodeRS(Rec);

#endif
	/* --- real life sample --- */
 	RealRec(Rec);
	DecodeRS(Rec);

 	RealRec(Rec);
	Rec[0] = 1;
	DecodeRS(Rec);

	printf("\n");
}

static	void	TimingTest()
{
	int	i,j;
	int	j_max=100;

  for(j=0;j<j_max;j++)
   {
	for(i=0;i<P_LEN;i++)
	   Rec[0] = 0;

 	Rec[0] = 1;
	/* Syn_Calc(SynP,Hp,Rec,P_RANK,P_LEN); */
	DecodeRS(Rec);

	for(i=1;i<P_LEN;i++)
	 {
	 	Rec[i-1] = 0;
	 	Rec[i]   = 1;
		/* Syn_Calc(SynP,Hp,Rec,P_RANK,P_LEN); */
		DecodeRS(Rec);
	 }
   }
  printf("\b\nDone: %d times\n",24*j_max);
}
/* =========================================================================== */
void	main(int argc, char *argv[])
{
	if (argc == 1)
 	 	Check_Syndrome2();
 	else
 		TimingTest();
}

