/* :ts=4
*
*	libinit.c
*
*	William A. Ware						D317
*
*****************************************************************************
*   This information is CONFIDENTIAL and PROPRIETARY						*
*   Copyright 1993, Silent Software, Incorporated.							*
*   All Rights Reserved.													*
****************************************************************************/

#include <exec/types.h>
#include <exec/nodes.h>
#include <exec/resident.h>
#include <exec/libraries.h>
#include <exec/memory.h>
#include <libraries/dos.h>
#include <proto/exec.h>
#include <proto/dos.h>

#include "version.h"

/* #define ROM */

extern char __far LibID[];
extern char __far LibName[];


/* A HANDY MACRO FOR MAKEING VERSIONS -- USE SECOND ONE */

#define VSTRA(ver,rev)	#ver"."#rev
#define VERSIONSTR(ver,rev)		VSTRA(ver,rev)




//typedef LONG (*PFL)();   /* pointer to function returning 32-bit int		*/

/* library initialization table, used for AUTOINIT libraries				*/
struct InitTable { 
	ULONG		 *it_DataSize;  	 /* library data space size 		*/ 
	PFL 		 *it_FuncTable; 	 /* table of entry points			*/ 
	APTR		 it_DataInit;		 /* table of data initializers  	*/ 
	PFL 		 it_InitFunc;		 /* initialization function to run  */
};


/*****************************************
* EXTERNAL REFERENCES GENERATED BY BLINK *
*****************************************/

extern PFL _LibFuncTab[];	/* table of library functions generated by blink */

extern char __far RESLEN;
extern long __far NEWDATAL; /* Generated by BLINK */
#define DATASIZE  ((long)&RESLEN)
#define DATAWORDS ((long)&NEWDATAL)

extern long __far _Libmergeddata;	/* Need this to determine start 
								 	 * of MERGED DATA */
extern long __far LinkerDB;

ULONG __asm _LibExpunge( register __a6 struct Library *libbase );
ULONG __asm _LibInit( register __a0 APTR seglist,
							   register __d0 struct Library *libbase );

struct InitTable __far _LibInitTab =  
{ 
	(long *)(sizeof(struct Library)), 
	_LibFuncTab, 
	NULL,						 /* will initialize my own data */ 
	_LibInit,
};



/*--------------------------- BASIC LIBRARY FUNCTIONS ---------------------*/

__asm ULONG _LibInit(	register __a0 APTR seglist,
						register __d0 struct Library *libbase )
{	
	/* init. library structure (since I don't do automatic data init.) */
	libbase->lib_Node.ln_Type = NT_LIBRARY;
	libbase->lib_Node.ln_Name =  LibName;
	libbase->lib_Flags = LIBF_SUMUSED | LIBF_CHANGED;
	libbase->lib_Version = 1;
	libbase->lib_Revision = REVISION;
	libbase->lib_IdString = (APTR) LibID;
	return ( (ULONG) libbase );
}




LONG __asm _LibOpen( register __a6 struct Library *libbase )
{ 
	/* mark us as having another customer */ 
	libbase->lib_OpenCnt++; 
	
	/* clear delayed expunges (standard procedure)  			  */ 
	libbase->lib_Flags &= ~LIBF_DELEXP; 
	
	return ( (LONG) libbase );
}



ULONG __asm _LibClose( register __a6 struct Library *libbase )
{ 
	ULONG retval = 0; 
	
	if (( --libbase->lib_OpenCnt == 0 ) && 
		( libbase->lib_Flags & LIBF_DELEXP )) 
	{ 
		/* no more people have me open, 
		 * and I have a delayed expunge pending 
		 */ 
	 	retval = _LibExpunge( libbase ); /* return segment list 	   */
	}
	return (retval);
}



ULONG __asm _LibExpunge( register __a6 struct Library *libbase )
{ 
	libbase->lib_Flags &= ~LIBF_DELEXP;
	return(NULL);
}


