€ˆDEVICES_AUDIO_H€DEVICES_AUDIO_HˆºŒ"exec/io.h"‡€AUDIONAME "audio.device"€ADHARD_CHANNELS 4€ADALLOC_MINPREC -128€ADALLOC_MAXPREC 127€ADCMD_FREE (CMD_NONSTD+0)€ADCMD_SETPREC (CMD_NONSTD+1)€ADCMD_FINISH (CMD_NONSTD+2)€ADCMD_PERVOL (CMD_NONSTD+3)€ADCMD_LOCK (CMD_NONSTD+4)€ADCMD_WAITCYCLE (CMD_NONSTD+5)€ADCMDB_NOUNIT 5€ADCMDF_NOUNIT (1<<5)€ADCMD_ALLOCATE (ADCMDF_NOUNIT+0)€ADIOB_PERVOL 4€ADIOF_PERVOL (1<<4)€ADIOB_SYNCCYCLE 5€ADIOF_SYNCCYCLE (1<<5)€ADIOB_NOWAIT 6€ADIOF_NOWAIT (1<<6)€ADIOB_WRITEMESSAGE 7€ADIOF_WRITEMESSAGE (1<<7)€ADIOERR_NOALLOCATION -10€ADIOERR_ALLOCFAILED -11€ADIOERR_CHANNELSTOLEN -12
ƒIOAudio{
ƒIORequest ioa_Request;
˜ioa_AllocKey;
Š*ioa_Data;
—ioa_Length;
‰ioa_Period;
‰ioa_Volume;
‰ioa_Cycles;
ƒ¯ioa_WriteMsg;
};‡