€ˆDEVICES_CONUNIT_H€DEVICES_CONUNIT_Hˆ¸Œ"exec/ports.h"‡ˆDEVICES_CONSOLE_HŒ"devices/console.h"‡ˆDEVICES_KEYMAP_HŒ"devices/keymap.h"‡ˆDEVICES_INPUTEVENT_HŒ"devices/inputevent.h"‡€PMB_ASM (M_LNM+1)€PMB_AWM (PMB_ASM+1)€MAXTABS 80
ƒConUnit{
ƒ©cu_MP;
ƒWindow*cu_Window;
˜cu_XCP;
˜cu_YCP;
˜cu_XMax;
˜cu_YMax;
˜cu_XRSize;
˜cu_YRSize;
˜cu_XROrigin;
˜cu_YROrigin;
˜cu_XRExtant;
˜cu_YRExtant;
˜cu_XMinShrink;
˜cu_YMinShrink;
˜cu_XCCP;
˜cu_YCCP;
ƒKeyMap cu_KeyMapStruct;
‰cu_TabStops[MAXTABS];
šcu_Mask;
šcu_FgPen;
šcu_BgPen;
šcu_AOLPen;
šcu_DrawMode;
šcu_AreaPtSz;
”cu_AreaPtrn;
Šcu_Minterms[8];
ƒTextFont*cu_Font;
Šcu_AlgoStyle;
Šcu_TxFlags;
‰cu_TxHeight;
‰cu_TxWidth;
‰cu_TxBaseline;
‰cu_TxSpacing;
Šcu_Modes[(PMB_AWM+7)/8];
Šcu_RawEvents[(IECLASS_MAX+7)/8];
};‡