€ˆDEVICES_GAMEPORT_H€DEVICES_GAMEPORT_H€GPD_READEVENT (CMD_NONSTD+0)€GPD_ASKCTYPE (CMD_NONSTD+1)€GPD_SETCTYPE (CMD_NONSTD+2)€GPD_ASKTRIGGER (CMD_NONSTD+3)€GPD_SETTRIGGER (CMD_NONSTD+4)€GPTB_DOWNKEYS 0€GPTF_DOWNKEYS (1<<0)€GPTB_UPKEYS 1€GPTF_UPKEYS (1<<1)
ƒGamePortTrigger{
‰gpt_Keys;
‰gpt_Timeout;
‰gpt_XDelta;
‰gpt_YDelta;
};€GPCT_ALLOCATED -1€GPCT_NOCONTROLLER 0€GPCT_MOUSE 1€GPCT_RELJOYSTICK 2€GPCT_ABSJOYSTICK 3€GPDERR_SETCTYPE 1‡