ÄàDEVICES_HARDBLOCKS_HÄDEVICES_HARDBLOCKS_H
ÉRigidDiskBlock{
órdb_ID;
órdb_SummedLongs;
írdb_ChkSum;
órdb_HostID;
órdb_BlockBytes;
órdb_Flags;
órdb_BadBlockList;
órdb_PartitionList;
órdb_FileSysHeaderList;
órdb_DriveInit;
órdb_Reserved1[6];
órdb_Cylinders;
órdb_Sectors;
órdb_Heads;
órdb_Interleave;
órdb_Park;
órdb_Reserved2[3];
órdb_WritePreComp;
órdb_ReducedWrite;
órdb_StepRate;
órdb_Reserved3[5];
órdb_RDBBlocksLo;
órdb_RDBBlocksHi;
órdb_LoCylinder;
órdb_HiCylinder;
órdb_CylBlocks;
órdb_AutoParkSeconds;
órdb_Reserved4[2];
Ñrdb_DiskVendor[8];
Ñrdb_DiskProduct[16];
Ñrdb_DiskRevision[4];
Ñrdb_ControllerVendor[8];
Ñrdb_ControllerProduct[16];
Ñrdb_ControllerRevision[4];
órdb_Reserved5[10];
};ÄIDNAME_RIGIDDISK (((ç)'R'<<24)|((ç)'D'<<16)|('S'<<8)|('K'))ÄRDB_LOCATION_LIMIT 16ÄRDBFB_LAST 0ÄRDBFF_LAST 1LÄRDBFB_LASTLUN 1ÄRDBFF_LASTLUN 2LÄRDBFB_LASTTID 2ÄRDBFF_LASTTID 4LÄRDBFB_NORESELECT 3ÄRDBFF_NORESELECT 8LÄRDBFB_DISKID 4ÄRDBFF_DISKID 16LÄRDBFB_CTRLRID 5ÄRDBFF_CTRLRID 32L
ÉBadBlockEntry{
óbbe_BadBlock;
óbbe_GoodBlock;
};
ÉBadBlockBlock{
óbbb_ID;
óbbb_SummedLongs;
íbbb_ChkSum;
óbbb_HostID;
óbbb_Next;
óbbb_Reserved;
ÉBadBlockEntry bbb_BlockPairs[61];
};ÄIDNAME_BADBLOCK (((ç)'B'<<24)|((ç)'A'<<16)|('D'<<8)|('B'))
ÉPartitionBlock{
ópb_ID;
ópb_SummedLongs;
ípb_ChkSum;
ópb_HostID;
ópb_Next;
ópb_Flags;
ópb_Reserved1[2];
ópb_DevFlags;
äpb_DriveName[32];
ópb_Reserved2[15];
ópb_Environment[17];
ópb_EReserved[15];
};ÄIDNAME_PARTITION (((ç)'P'<<24)|((ç)'A'<<16)|('R'<<8)|('T'))ÄPBFB_BOOTABLE 0ÄPBFF_BOOTABLE 1LÄPBFB_NOMOUNT 1ÄPBFF_NOMOUNT 2L
ÉFileSysHeaderBlock{
ófhb_ID;
ófhb_SummedLongs;
ífhb_ChkSum;
ófhb_HostID;
ófhb_Next;
ófhb_Flags;
ófhb_Reserved1[2];
ófhb_DosType;
ófhb_Version;
ófhb_PatchFlags;
ófhb_Type;
ófhb_Task;
ófhb_Lock;
ófhb_Handler;
ófhb_StackSize;
ífhb_Priority;
ífhb_Startup;
ífhb_SegListBlocks;
ífhb_GlobalVec;
ófhb_Reserved2[23];
ófhb_Reserved3[21];
};ÄIDNAME_FILESYSHEADER (((ç)'F'<<24)|((ç)'S'<<16)|('H'<<8)|('D'))
ÉLoadSegBlock{
ólsb_ID;
ólsb_SummedLongs;
ílsb_ChkSum;
ólsb_HostID;
ólsb_Next;
ólsb_LoadData[123];
};ÄIDNAME_LOADSEG (((ç)'L'<<24)|((ç)'S'<<16)|('E'<<8)|('G'))á