€ˆDEVICES_INPUTEVENT_H€DEVICES_INPUTEVENT_HˆDEVICES_TIMER_HŒ"devices/timer.h"‡€IECLASS_NULL 0€IECLASS_RAWKEY 1€IECLASS_RAWMOUSE 2€IECLASS_EVENT 3€IECLASS_POINTERPOS 4€IECLASS_TIMER 6€IECLASS_GADGETDOWN 7€IECLASS_GADGETUP 8€IECLASS_REQUESTER 9€IECLASS_MENULIST 10€IECLASS_CLOSEWINDOW 11€IECLASS_SIZEWINDOW 12€IECLASS_REFRESHWINDOW 13€IECLASS_NEWPREFS 14€IECLASS_DISKREMOVED 15€IECLASS_DISKINSERTED 16€IECLASS_ACTIVEWINDOW 17€IECLASS_INACTIVEWINDOW 18€IECLASS_MAX 18€IECODE_UP_PREFIX 128€IECODE_KEY_CODE_FIRST 0€IECODE_KEY_CODE_LAST 119€IECODE_COMM_CODE_FIRST 120€IECODE_COMM_CODE_LAST 127€IECODE_C0_FIRST 0€IECODE_C0_LAST 31€IECODE_ASCII_FIRST 32€IECODE_ASCII_LAST 126€IECODE_ASCII_DEL 127€IECODE_C1_FIRST 128€IECODE_C1_LAST 159€IECODE_LATIN1_FIRST 160€IECODE_LATIN1_LAST 255€IECODE_LBUTTON 104€IECODE_RBUTTON 105€IECODE_MBUTTON 106€IECODE_NOBUTTON 255€IECODE_NEWACTIVE 1€IECODE_REQSET 1€IECODE_REQCLEAR 0€IEQUALIFIER_LSHIFT 1€IEQUALIFIER_RSHIFT 2€IEQUALIFIER_CAPSLOCK 4€IEQUALIFIER_CONTROL 8€IEQUALIFIER_LALT 16€IEQUALIFIER_RALT 32€IEQUALIFIER_LCOMMAND 64€IEQUALIFIER_RCOMMAND 128€IEQUALIFIER_NUMERICPAD 256€IEQUALIFIER_REPEAT 512€IEQUALIFIER_INTERRUPT 0x400€IEQUALIFIER_MULTIBROADCAST 0x800€IEQUALIFIER_MIDBUTTON 0x1000€IEQUALIFIER_RBUTTON 0x2000€IEQUALIFIER_LEFTBUTTON 0x4000€IEQUALIFIER_RELATIVEMOUSE 0x8000€IEQUALIFIERB_LSHIFT 0€IEQUALIFIERB_RSHIFT 1€IEQUALIFIERB_CAPSLOCK 2€IEQUALIFIERB_CONTROL 3€IEQUALIFIERB_LALT 4€IEQUALIFIERB_RALT 5€IEQUALIFIERB_LCOMMAND 6€IEQUALIFIERB_RCOMMAND 7€IEQUALIFIERB_NUMERICPAD 8€IEQUALIFIERB_REPEAT 9€IEQUALIFIERB_INTERRUPT 10€IEQUALIFIERB_MULTIBROADCAST 11€IEQUALIFIERB_MIDBUTTON 12€IEQUALIFIERB_RBUTTON 13€IEQUALIFIERB_LEFTBUTTON 14€IEQUALIFIERB_RELATIVEMOUSE 15
ƒInputEvent{
ƒInputEvent*ie_NextEvent;
Šie_Class;
Šie_SubClass;
‰ie_Code;
‰ie_Qualifier;
«{
ƒ{
˜ie_x;
˜ie_y;
}ie_xy;
”ie_addr;
}ie_position;
ƒtimeval ie_TimeStamp;
};€ie_X ie_position.ie_xy.ie_x€ie_Y ie_position.ie_xy.ie_y€ie_EventAddress ie_position.ie_addr‡