€ˆDEVICES_PARALLEL_H€DEVICES_PARALLEL_HˆºŒ"exec/io.h"‡
ƒIOPArray{
—PTermArray0;
—PTermArray1;
};
ƒIOExtPar{
ƒIOStdReq IOPar;
—io_PExtFlags;
Šio_Status;
Šio_ParFlags;
ƒIOPArray io_PTermArray;
};€PARB_SHARED 5€PARF_SHARED (1<<5)€PARB_RAD_BOOGIE 3€PARF_RAD_BOOGIE (1<<3)€PARB_EOFMODE 1€PARF_EOFMODE (1<<1)€IOPARB_QUEUED 6€IOPARF_QUEUED (1<<6)€IOPARB_ABORT 5€IOPARF_ABORT (1<<5)€IOPARB_ACTIVE 4€IOPARF_ACTIVE (1<<4)€IOPTB_RWDIR 3€IOPTF_RWDIR (1<<3)€IOPTB_PARSEL 2€IOPTF_PARSEL (1<<2)€IOPTB_PAPEROUT 1€IOPTF_PAPEROUT (1<<1)€IOPTB_PARBUSY 0€IOPTF_PARBUSY (1<<0)€PARALLELNAME "parallel.device"€PDCMD_QUERY (CMD_NONSTD)€PDCMD_SETPARAMS (CMD_NONSTD+1)€ParErr_DevBusy 1€ParErr_BufTooBig 2€ParErr_InvParam 3€ParErr_LineErr 4€ParErr_NotOpen 5€ParErr_PortReset 6€ParErr_InitErr 7‡