€ˆDEVICES_PRTGFX_H€DEVICES_PRTGFX_H€PCMYELLOW 0€PCMMAGENTA 1€PCMCYAN 2€PCMBLACK 3€PCMBLUE PCMYELLOW€PCMGREEN PCMMAGENTA€PCMRED PCMCYAN€PCMWHITE PCMBLACK
«colorEntry{
—colorLong;
ŠcolorByte[4];
šcolorSByte[4];
};
ƒPrtInfo{
‚(*pi_render)();
ƒRastPort*pi_rp;
ƒRastPort*pi_temprp;
‰*pi_RowBuf;
‰*pi_HamBuf;
«colorEntry*pi_ColorMap;
«colorEntry*pi_ColorInt;
«colorEntry*pi_HamInt;
«colorEntry*pi_Dest1Int;
«colorEntry*pi_Dest2Int;
‰*pi_ScaleX;
‰*pi_ScaleXAlt;
Š*pi_dmatrix;
‰*pi_TopBuf;
‰*pi_BotBuf;
‰pi_RowBufSize;
‰pi_HamBufSize;
‰pi_ColorMapSize;
‰pi_ColorIntSize;
‰pi_HamIntSize;
‰pi_Dest1IntSize;
‰pi_Dest2IntSize;
‰pi_ScaleXSize;
‰pi_ScaleXAltSize;
‰pi_PrefsFlags;
—pi_special;
‰pi_xstart;
‰pi_ystart;
‰pi_width;
‰pi_height;
—pi_pc;
—pi_pr;
‰pi_ymult;
‰pi_ymod;
˜pi_ety;
‰pi_xpos;
‰pi_threshold;
‰pi_tempwidth;
‰pi_flags;
};‡