€ˆDEVICES_SERIAL_H€DEVICES_SERIAL_HˆºŒ"exec/io.h"‡
ƒIOTArray{
—TermArray0;
—TermArray1;
};€SER_DEFAULT_CTLCHAR 0x11130000
ƒIOExtSer{
ƒIOStdReq IOSer;
—io_CtlChar;
—io_RBufLen;
—io_ExtFlags;
—io_Baud;
—io_BrkTime;
ƒIOTArray io_TermArray;
Šio_ReadLen;
Šio_WriteLen;
Šio_StopBits;
Šio_SerFlags;
‰io_Status;
};€SDCMD_QUERY CMD_NONSTD€SDCMD_BREAK (CMD_NONSTD+1)€SDCMD_SETPARAMS (CMD_NONSTD+2)€SERB_XDISABLED 7€SERF_XDISABLED (1<<7)€SERB_EOFMODE 6€SERF_EOFMODE (1<<6)€SERB_SHARED 5€SERF_SHARED (1<<5)€SERB_RAD_BOOGIE 4€SERF_RAD_BOOGIE (1<<4)€SERB_QUEUEDBRK 3€SERF_QUEUEDBRK (1<<3)€SERB_7WIRE 2€SERF_7WIRE (1<<2)€SERB_PARTY_ODD 1€SERF_PARTY_ODD (1<<1)€SERB_PARTY_ON 0€SERF_PARTY_ON (1<<0)€IO_STATB_XOFFREAD 12€IO_STATF_XOFFREAD (1<<12)€IO_STATB_XOFFWRITE 11€IO_STATF_XOFFWRITE (1<<11)€IO_STATB_READBREAK 10€IO_STATF_READBREAK (1<<10)€IO_STATB_WROTEBREAK 9€IO_STATF_WROTEBREAK (1<<9)€IO_STATB_OVERRUN 8€IO_STATF_OVERRUN (1<<8)€SEXTB_MSPON 1€SEXTF_MSPON (1<<1)€SEXTB_MARK 0€SEXTF_MARK (1<<0)€SerErr_DevBusy 1€SerErr_BufErr 4€SerErr_InvParam 5€SerErr_LineErr 6€SerErr_ParityErr 9€SerErr_TimerErr 11€SerErr_BufOverflow 12€SerErr_NoDSR 13€SerErr_DetectedBreak 15°DEVICES_SERIAL_H_OBSOLETE€SerErr_BaudMismatch 2€SerErr_InvBaud 3€SerErr_NotOpen 7€SerErr_PortReset 8€SerErr_InitErr 10€SerErr_NoCTS 14€IOSTB_XOFFREAD 4€IOSTF_XOFFREAD (1<<4)€IOSTB_XOFFWRITE 3€IOSTF_XOFFWRITE (1<<3)€IOSTB_READBREAK 2€IOSTF_READBREAK (1<<2)€IOSTB_WROTEBREAK 1€IOSTF_WROTEBREAK (1<<1)€IOSTB_OVERRUN 0€IOSTF_OVERRUN (1<<0)€IOSERB_BUFRREAD 7€IOSERF_BUFRREAD (1<<7)€IOSERB_QUEUED 6€IOSERF_QUEUED (1<<6)€IOSERB_ABORT 5€IOSERF_ABORT (1<<5)€IOSERB_ACTIVE 4€IOSERF_ACTIVE (1<<4)‡€SERIALNAME "serial.device"‡