##########################################################################

MAKEFILE=	Makefile
MAKEMETA=	/usr/commodore/amiga/V37/tools/makemeta
SRCDIRPATH=	workbench/fonts/opal
SRCDIR=		9
SUBSYSNAME=	9
DISKPATH=	fonts/opal/9

AFILES=		9.asm
OFILES=		9.obj

all:		${SUBSYSNAME}.ld

.INCLUDE=${MAKEMETA}
SYMBOLOPT=
