/* used to calculate offsets to fields in intuition base
 * $Id: offsets.c,v 38.0 91/06/12 14:27:49 peter Exp $
 */

#include <exec/types.h>
#include "intuall.h"
#include "preferences.h"
#undef printf

main()
{
    struct IntuitionBase *IBase = (struct IntuitionBase *) 0;
    struct Preferences *PBase = (struct Preferences *) 0;

    printf("*\tioffsets.i --\n");
    printf("*\tautomatically generated by offsets.c\n");
    printf("ib_sizeof\tequ\t$%lx\n", sizeof (struct IntuitionBase));

    printf("\txdef\t_SysBaseOffset\n");
    printf("_SysBaseOffset\tequ\t$%lx\n", &IBase->SysBase);

    printf("\txdef\t_GfxBaseOffset\n");
    printf("_GfxBaseOffset\tequ\t$%lx\n", &IBase->GfxBase);

    printf("\txdef\t_LayersBaseOffset\n");
    printf("_LayersBaseOffset\tequ\t$%lx\n", &IBase->LayersBase);

    printf("\txdef\t_UtilityBaseOffset\n");
    printf("_UtilityBaseOffset\tequ\t$%lx\n", &IBase->UtilityBase);

    printf("\txdef\t_KeymapBaseOffset\n");
    printf("_KeymapBaseOffset\tequ\t$%lx\n", &IBase->KeymapBase);

#if 0
    /* display library is/was a development module	*/
    printf("\txdef\t_DisplayBaseOffset\n");
    printf("_DisplayBaseOffset\tequ\t$%lx\n", &IBase->DisplayBase);
#endif

    printf("\n*\toffset to semaphores: $%lx\n", IBase->ISemaphore);

    printf("*\tview offset: $%lx\n", &PBase->ViewXOffset);

}
