
char *sys_errlist[] = {
	"Unknown error code"
	"User is not owner"
	"No such file or directory"
	"No such process"
	"Interrupted system call"
	"I/O error"
	"No such device or address"
	"Arg list is too long"
	"Exec format error"
	"Bad file number"
	"No child process"
	"No more processes allowed"
	"No memory available"
	"Access denied"
	"Bad address"
	"Bulk device required"
	"Resource is busy"
	"File already exists"
	"Cross-device link"
	"No such device"
	"Not a directory"
	"Is a directory"
	"Invalid argument"
	"No more files (units) allowed"
	"No more files (units) allowed for this process"
	"Not a terminal"
	"Text file is busy"
	"File is too large"
	"No space left"
	"Seek issued to pipe"
	"Read-only file system"
	"Too many links"
	"Broken pipe"
	"Math function argument error"
	"Math function result is out of range"
};


int sys_nerr =  sizeof(sys_errlist) / sizeof(sys_errlist[0]);
