

#include <exec/types.h>


enum AppStringsID
{
    MSG_NORMAL,
    MSG_ERROR,
    MSG_ERROR_NO_STRING_LINE,
    MSG_ERROR_NO_TOKEN,
    MSG_ERROR_NO_LPAREN,
    MSG_ERROR_NO_RPAREN,
    MSG_ERROR_NO_SLASH,
    MSG_ERROR_JUNK_AFTER_TOKEN,
    MSG_ERROR_INVALID_TOKEN,
    MSG_ERROR_TOKEN_ABSENT,
    MSG_ERROR_STRING_TOO_SHORT,
    MSG_ERROR_STRING_TOO_LONG,
    MSG_ERROR_NEGATIVE_MINLEN,
    MSG_ERROR_NEGATIVE_MAXLEN,
    MSG_ERROR_NEGATIVE_ORDER,
    MSG_ERROR_MISSING_ORDER,
    MSG_ERROR_ORDER_TOO_LARGE,
    MSG_ERROR_BAD_CMD_SIZE,
    MSG_ERROR_BAD_CMD,
    MSG_ERROR_TOKEN_DEFINED_TWICE,
    MSG_ERROR_ID_DEFINED_TWICE,
    MSG_ERROR_NO_COMMAND,
    MSG_ERROR_UNKNOWN_COMMAND,
    MSG_ERROR_BAD_CODESET,
    MSG_ERROR_BAD_RCSID,
    MSG_ERROR_BAD_LENGTHBYTES,
    MSG_ERROR_WRITING_CAT,
    MSG_ERROR_WRITING_CTFILE,
    MSG_ERROR_WRITING_CFILE,
    MSG_ERROR_WRITING_ASMFILE,
    MSG_ERROR_WRITING_M2FILE,
    MSG_ERROR_WRITING_OBJFILE,

    MSG_WARN_BAD_FORMAT_CMD,
    MSG_WARN_SAME_STRINGS,
    MSG_WARN_NO_ELLIPSIS,

    MSG_CTHEADER,
    MSG_CCOMMENT,
    MSG_ASMCOMMENT,
    MSG_M2COMMENT,
    MSG_VALID_DESCRIPTOR,
    MSG_VALID_TRANSLATION
};


STRPTR GetString(enum AppStringsID id);
