##########################################################################
 
MAKEFILE=	Makefile
MAKEMETA=	/usr/commodore/amiga/V37/tools/makemeta

SUBDIRS=	11 13 15 18 24

all:            ${SUBDIRS}

.INCLUDE=${MAKEMETA}
