##########################################################################

MAKEFILE=	Makefile
MAKEMETA=	/usr/commodore/amiga/V37/tools/makemeta
SRCDIRPATH=	workbench/fonts/diamond
SRCDIR=		20
SUBSYSNAME=	20
DISKPATH=	fonts/diamond/20

AFILES=		20.asm
OFILES=		20.obj

all:		${SUBSYSNAME}.ld

.INCLUDE=${MAKEMETA}
SYMBOLOPT=
