# NATIVE BUILD ONLY

SU    =
SYSCHECK = -dSYSCHECK=1
CC    =lc
CCF   =-b0 -cfst -d $(SYSCHECK) -ms -O -q500w1e -rr1 -v -iv36:include -iv36:inc.lattice
xAS  = assem
AS  = asm $(SYSCHECK)
xASF = -c w200000 -i fh1:languages/latticec5.02/lc/include -o
xASF = -c w200000 -i v36:include -o
ASF = -iv36:include/
LN    =blink
LNF   =ND SC SD BATCH 
LIBS  =lib:debug.lib+lib:amiga.lib+lib:lcr.lib+endcode.lib

SRC=bmrtag.asm scrtag.asm stub.asm bootmenu.c syscheck.c support.c

OBJ=bmrtag.o scrtag.o stub.o bootmenu.o syscheck.o support.o

.asm.o:
   $(AS) $(ASF) $>.asm

.c.o:
   $(CC) $(CCF) $>

bootmenu.ld: $(OBJ) makefile endcode.lib
   v36:aug/bin/bumprev 36 bootmenu_rev
   v36:aug/bin/bumprev 36 syscheck_rev
   delete bootmenu_rev.h
   delete syscheck_rev.h
   $(AS) $(ASF) bmrtag.asm
   $(AS) $(ASF) scrtag.asm
   $(LN) $(LNF) FROM $(SU) $(OBJ) LIB $(LIBS) TO $@ MAP bootmenu.map,F,H,L,O,S,X 

endcode.lib: endcode.asm
   assem -o endocde.lib endcode.asm

release:
   copy \#? v36:src/kickstart/bootmenu
   spat "chmod 775"      v36:src/kickstart/bootmenu/\#?
   delete v36:src/kickstart/bootmenu/\#?.o
