*** This file generated on Fri Jun 30 20:08:02 1989
*** $Header: gen-lib.ml,v 33.1 86/03/18 11:47:40 neil Exp $
*** DO NOT EDIT: FILE BUILT AUTOMATICALLY
	FUNCDEF	SPFix
	FUNCDEF	SPFlt
	FUNCDEF	SPCmp
	FUNCDEF	SPTst
	FUNCDEF	SPAbs
	FUNCDEF	SPNeg
	FUNCDEF	SPAdd
	FUNCDEF	SPSub
	FUNCDEF	SPMul
	FUNCDEF	SPDiv
	FUNCDEF	SPFloor
	FUNCDEF	SPCeil
