/* RMAKE (h/protos.h) Prototype generation (Version 3.22)
** RMAKE Copyright © 1990,91,92 Mitchell/Ware Systems, Inc.
** RMAKE All Rights Reserved.
**
** This and other files GENERATED by the RMAKE system
** are the sole property of the non-commercial user; however the RMAKE
** System is the sole property of Mitchell/Ware Systems and
** available only for non-commercial use. Commercial versions of
** RMAKE can be obtained by contacting Mitchell/Ware Systems
** at (215)524-9100 or 'f.mitchell' on BIX.
*/


/* Prototypes for functions defined in c/CreateRastPortBitMap.c */
struct RastPort *CreateRastPortBitMap(long width,
                                      long height,
                                      long depth,
                                      long vectors,
                                      BOOL clip);
void FreeRastPortBitMap(struct RastPort *rp);
/* Prototypes for functions defined in c/WBCliArgs.c */
struct WBCli *WBCliArgs(struct TagItem *array);
char *FilterTemplateVec(char *template);
BOOL OpenAllWBCliLibraries(struct WBCli *wbcli);
void CloseAllWBCliLibraries(struct WBCli *wbcli);
struct WBCli *WBCliArgsTags(unsigned long Tag, ...);
struct WBCGui *AddGuiEntry(struct WBCli *wbcli);
long ParseWBCliTemplate(struct WBCli *wbcli,
                        char *template,
                        ULONG *args);
void FreeWBCli(struct WBCli *wbcli);
/* Prototypes for functions defined in c/StrToDouble.c */
double StrToDouble(char *s,
                   long *plen);
/* Prototypes for functions defined in c/MWReadArgs.c */
struct RDArgs *MWReadArgs(UBYTE *template,
                          LONG *array,
                          struct RDArgs *rdargs);
long MWReadItem(UBYTE *buffer,
                long maxchars,
                struct CSource *cs,
                char delim);
long MWReadChar(struct CSource *cs);
BOOL MWUnReadChar(struct CSource *cs);
/* Prototypes for functions defined in c/MWTokenizer.c */
/* Prototypes for functions defined in c/LRand.c */
struct LREnv *LROpen(ULONG Seed,
                     ULONG NumRegs,
                     ULONG Tap);
void LRClose(struct LREnv *lr);
ULONG LRand(struct LREnv *lr);
/* Prototypes for functions defined in c/MakeRDA.c */
struct RDArgs *MakeRDA(char *buf);
void DestroyRDA(struct RDArgs *rda);
/* Prototypes for functions defined in c/RXPrintf.c */
UBYTE *RXPrintf(char *fmt,
                ULONG p1, ...);
