;****************************************************************************
;
; mes.inc contains external messages for PC janus handler
;
;****************************************************************************
.xlist
;
extrn	 inmsg:byte
extrn	 loadmsg:byte
extrn	 BaseMsg:byte
extrn	 IntsMsg:byte
extrn	 ParasMsg:byte
extrn	 BufferMsg:byte
extrn	 DosMsgA:byte
extrn	 DosMsgN:byte
extrn	 HWMsgP:byte
extrn	 HWMsgPC:byte
extrn	 HWMsgR:byte
extrn	 IntTblMes:byte
extrn	 FoundIntMes:byte
extrn	 ExeIntMes:byte
extrn	 ESDI_Mes:byte
extrn	 TestIntMes:byte
extrn	 IntCtrlMes:byte
extrn	 RegMsg:byte
extrn	 NoHanMes:byte
extrn	 NoIntMes:byte
extrn	 NoDriveMsg:byte
extrn	 NoPartMsg:byte
extrn	 LoadErrMsg:byte
extrn	 Diskmsg1:byte
;
.list

