##########################################################################

MAKEFILE=	Makefile
MAKEMETA=	/usr/commodore/amiga/V37/tools/makemeta
SRCDIRPATH=	workbench/fonts/helvetica
SRCDIR=		18
SUBSYSNAME=	18
DISKPATH=	fonts/helvetica/18

AFILES=		18.asm
OFILES=		18.obj

all:		${SUBSYSNAME}.ld

.INCLUDE=${MAKEMETA}
SYMBOLOPT=
