€ˆGRAPHICS_GELS_H€GRAPHICS_GELS_H€SUSERFLAGS 255€VSPRITE 1€SAVEBACK 2€OVERLAY 4€MUSTDRAW 8€BACKSAVED 256€BOBUPDATE 512€GELGONE 0x400€VSOVERFLOW 0x800€BUSERFLAGS 255€SAVEBOB 1€BOBISCOMP 2€BWAITING 256€BDRAWN 512€BOBSAWAY 0x400€BOBNIX 0x800€SAVEPRESERVE 0x1000€OUTSTEP 0x2000€ANFRACSIZE 6€ANIMHALF 32€RINGTRIGGER 1ˆVUserStuff€VUserStuff•‡ˆBUserStuff€BUserStuff•‡ˆAUserStuff€AUserStuff•‡
ƒVSprite
{
ƒVSprite*NextVSprite;
ƒVSprite*PrevVSprite;
ƒVSprite*DrawPath;
ƒVSprite*ClearPath;
˜OldY,OldX;
˜¦;
˜Y,X;
˜Height;
˜Width;
˜Depth;
˜MeMask;
˜HitMask;
˜*ImageData;
˜*BorderLine;
˜*CollMask;
˜*SprColors;
ƒBob*VSBob;
šPlanePick;
šPlaneOnOff;
VUserStuff VUserExt;
};
ƒBob
{
˜¦;
˜*SaveBuffer;
˜*ImageShadow;
ƒBob*Before;
ƒBob*After;
ƒVSprite*BobVSprite;
ƒAnimComp*BobComp;
ƒDBufPacket*DBuffer;
BUserStuff BUserExt;
};
ƒAnimComp
{
˜¦;
˜Timer;
˜TimeSet;
ƒAnimComp*NextComp;
ƒAnimComp*PrevComp;
ƒAnimComp*NextSeq;
ƒAnimComp*PrevSeq;
˜(*AnimCRoutine)();
˜YTrans;
˜XTrans;
ƒAnimOb*HeadOb;
ƒBob*AnimBob;
};
ƒAnimOb
{
ƒAnimOb*NextOb,*PrevOb;
’Clock;
˜AnOldY,AnOldX;
˜AnY,AnX;
˜YVel,XVel;
˜YAccel,XAccel;
˜RingYTrans,RingXTrans;
˜(*AnimORoutine)();
ƒAnimComp*HeadComp;
AUserStuff AUserExt;
};
ƒDBufPacket
{
˜BufY,BufX;
ƒVSprite*BufPath;
˜*BufBuffer;
};€InitAnimate(animKey) {*(animKey)=œ;}€RemBob(b) {(b)->¦|=BOBSAWAY;}€B2NORM 0€B2SWAP 1€B2BOBBER 2
ƒcollTable
{
‚(*collPtrs[16])();
};‡