€ˆGRAPHICS_RASTPORT_H€GRAPHICS_RASTPORT_HˆGRAPHICS_GFX_HŒ<graphics/gfx.h>‡
ƒAreaInfo
{
•*VctrTbl;
•*VctrPtr;
š*FlagTbl;
š*FlagPtr;
•Count;
•MaxCount;
•FirstX,FirstY;
};
ƒTmpRas
{
š*RasPtr;
’Size;
};
ƒGelsInfo
{
šsprRsrvd;
Š¦;
ƒVSprite*gelHead,*gelTail;
˜*nextLine;
˜**lastColor;
ƒcollTable*collHandler;
Ÿleftmost,rightmost,topmost,bottommost;
”firstBlissObj,lastBlissObj;
};
ƒRastPort
{
ƒLayer*Layer;
ƒBitMap*BitMap;
™*AreaPtrn;
ƒTmpRas*TmpRas;
ƒAreaInfo*AreaInfo;
ƒGelsInfo*GelsInfo;
ŠMask;
šFgPen;
šBgPen;
šAOlPen;
šDrawMode;
šAreaPtSz;
šlinpatcnt;
šdummy;
™¦;
™LinePtrn;
•cp_x,cp_y;
Šminterms[8];
•PenWidth;
•PenHeight;
ƒTextFont*Font;
ŠAlgoStyle;
ŠTxFlags;
‰TxHeight;
‰TxWidth;
‰TxBaseline;
˜TxSpacing;
”*RP_User;
—longreserved[2];ˆGFX_RASTPORT_1_2
‰wordreserved[7];
Šreserved[8];‡
};€JAM1 0€JAM2 1€COMPLEMENT 2€INVERSVID 4€FRST_DOT 1€ONE_DOT 2€DBUFFER 4€AREAOUTLINE 8€NOCROSSFILL 32‡