€ˆGRAPHICS_VIEW_H€GRAPHICS_VIEW_HˆGRAPHICS_GFX_HŒ<graphics/gfx.h>‡ˆGRAPHICS_COPPER_HŒ<graphics/copper.h>‡
ƒColorMap
{
Š¦;
ŠType;
‰Count;
”ColorTable;
};
ƒViewPort
{
ƒViewPort*Next;
ƒColorMap*ColorMap;
ƒCopList*DspIns;
ƒCopList*SprIns;
ƒCopList*ClrIns;
ƒUCopList*UCopIns;
•DWidth,DHeight;
•DxOffset,DyOffset;
‰Modes;
ŠSpritePriorities;
Šreserved;
ƒRasInfo*RasInfo;
};
ƒView
{
ƒViewPort*ViewPort;
ƒcprlist*LOFCprList;
ƒcprlist*SHFCprList;
ŸDyOffset,DxOffset;
‰Modes;
};€PFBA 64€DUALPF 0x400€HIRES 0x8000€LACE 4€HAM 0x800€SPRITES 0x4000€VP_HIDE 0x2000€GENLOCK_AUDIO 256€GENLOCK_VIDEO 2€EXTRA_HALFBRITE 128
ƒRasInfo
{
ƒRasInfo*Next;
ƒBitMap*BitMap;
•RxOffset,RyOffset;
};‡