ÄàµÄµ
É¨{
É¨*ln_Succ;
É¨*ln_Pred;
äln_Type;
öln_Pri;
Ñ*ln_Name;
};
ÉMinNode{
ÉMinNode*mln_Succ;
ÉMinNode*mln_Pred;
};ÄNT_UNKNOWN 0ÄNT_TASK 1ÄNT_INTERRUPT 2ÄNT_DEVICE 3ÄNT_MSGPORT 4ÄNT_MESSAGE 5ÄNT_FREEMSG 6ÄNT_REPLYMSG 7ÄNT_RESOURCE 8ÄNT_LIBRARY 9ÄNT_MEMORY 10ÄNT_SOFTINT 11ÄNT_FONT 12ÄNT_PROCESS 13ÄNT_SEMAPHORE 14ÄNT_SIGNALSEM 15ÄNT_BOOTNODE 16á