######################################################################
# MAKEMETA=	/usr/commodore/amiga/V${VERSION}/tools/makemeta
MAKEMETA=	/usr/commodore/amiga/V36/tools/makemeta

MAKEFILE=	Makefile
SRCDIRPATH=	include
SRCDIR=		clib
SUBSYSGROUP=	clib

EXTERNHFILES=	macros.h
INTERNHFILES=
HFILES=		${EXTERNHFILES} ${INTERNHFILES}

EXTERNIFILES=
INTERNIFILES=
IFILES=		${EXTERNIFILES} ${INTERNIFILES}

all:
		@echo "(${SRCDIRPATH}/${SRCDIR}: nothing to make)"

.INCLUDE=${MAKEMETA}
