
#define POINTER_PREFS
#define MSG_PREFS_NAME MSG_PTR_NAME
#define	MSG_OPEN_CLIP  MSG_PTR_OPEN_CLIPBOARD_STAT
#define	MSG_NO_GRAPHIC MSG_PTR_PASTE_GRAPHIC_STAT
#define MSG_REQ_LOAD   MSG_PTR_REQ_LOAD
#define MSG_REQ_SAVE   MSG_PTR_REQ_SAVE
