*** DO NOT EDIT: FILE BUILT AUTOMATICALLY
*** mathieeesingbas_lib.asm function offsets
	IDNT	mathieeesingbas_LVO
	SECTION	mathieeesingbas_LVO0
	XDEF	_LVOIEEESPFix
_LVOIEEESPFix EQU	-30
	XDEF	_LVOIEEESPFlt
_LVOIEEESPFlt EQU	-36
	XDEF	_LVOIEEESPCmp
_LVOIEEESPCmp EQU	-42
	XDEF	_LVOIEEESPTst
_LVOIEEESPTst EQU	-48
	XDEF	_LVOIEEESPAbs
_LVOIEEESPAbs EQU	-54
	XDEF	_LVOIEEESPNeg
_LVOIEEESPNeg EQU	-60
	XDEF	_LVOIEEESPAdd
_LVOIEEESPAdd EQU	-66
	XDEF	_LVOIEEESPSub
_LVOIEEESPSub EQU	-72
	XDEF	_LVOIEEESPMul
_LVOIEEESPMul EQU	-78
	XDEF	_LVOIEEESPDiv
_LVOIEEESPDiv EQU	-84
	XDEF	_LVOIEEESPFloor
_LVOIEEESPFloor EQU	-90
	XDEF	_LVOIEEESPCeil
_LVOIEEESPCeil EQU	-96
	END
