*** DO NOT EDIT: FILE BUILT AUTOMATICALLY
*** mathieeedoubbas_lib.asm function offsets
	IDNT	mathieeedoubbas_LVO
	SECTION	mathieeedoubbas_LVO0
	XDEF	_LVOIEEEDPFix
_LVOIEEEDPFix EQU	-30
	XDEF	_LVOIEEEDPFlt
_LVOIEEEDPFlt EQU	-36
	XDEF	_LVOIEEEDPCmp
_LVOIEEEDPCmp EQU	-42
	XDEF	_LVOIEEEDPTst
_LVOIEEEDPTst EQU	-48
	XDEF	_LVOIEEEDPAbs
_LVOIEEEDPAbs EQU	-54
	XDEF	_LVOIEEEDPNeg
_LVOIEEEDPNeg EQU	-60
	XDEF	_LVOIEEEDPAdd
_LVOIEEEDPAdd EQU	-66
	XDEF	_LVOIEEEDPSub
_LVOIEEEDPSub EQU	-72
	XDEF	_LVOIEEEDPMul
_LVOIEEEDPMul EQU	-78
	XDEF	_LVOIEEEDPDiv
_LVOIEEEDPDiv EQU	-84
	XDEF	_LVOIEEEDPFloor
_LVOIEEEDPFloor EQU	-90
	XDEF	_LVOIEEEDPCeil
_LVOIEEEDPCeil EQU	-96
	END
