*** DO NOT EDIT: FILE BUILT AUTOMATICALLY
*** mathffp_lib.asm function offsets
	IDNT	mathffp_LVO
	SECTION	mathffp_LVO0
	XDEF	_LVOSPFix
_LVOSPFix EQU	-30
	XDEF	_LVOSPFlt
_LVOSPFlt EQU	-36
	XDEF	_LVOSPCmp
_LVOSPCmp EQU	-42
	XDEF	_LVOSPTst
_LVOSPTst EQU	-48
	XDEF	_LVOSPAbs
_LVOSPAbs EQU	-54
	XDEF	_LVOSPNeg
_LVOSPNeg EQU	-60
	XDEF	_LVOSPAdd
_LVOSPAdd EQU	-66
	XDEF	_LVOSPSub
_LVOSPSub EQU	-72
	XDEF	_LVOSPMul
_LVOSPMul EQU	-78
	XDEF	_LVOSPDiv
_LVOSPDiv EQU	-84
	XDEF	_LVOSPFloor
_LVOSPFloor EQU	-90
	XDEF	_LVOSPCeil
_LVOSPCeil EQU	-96
	END
