*** DO NOT EDIT: FILE BUILT AUTOMATICALLY
*** mathieeesingtrans_lib.asm function offsets
	IDNT	mathieeesingtrans_LVO
	SECTION	mathieeesingtrans_LVO0
	XDEF	_LVOIEEESPAtan
_LVOIEEESPAtan EQU	-30
	XDEF	_LVOIEEESPSin
_LVOIEEESPSin EQU	-36
	XDEF	_LVOIEEESPCos
_LVOIEEESPCos EQU	-42
	XDEF	_LVOIEEESPTan
_LVOIEEESPTan EQU	-48
	XDEF	_LVOIEEESPSincos
_LVOIEEESPSincos EQU	-54
	XDEF	_LVOIEEESPSinh
_LVOIEEESPSinh EQU	-60
	XDEF	_LVOIEEESPCosh
_LVOIEEESPCosh EQU	-66
	XDEF	_LVOIEEESPTanh
_LVOIEEESPTanh EQU	-72
	XDEF	_LVOIEEESPExp
_LVOIEEESPExp EQU	-78
	XDEF	_LVOIEEESPLog
_LVOIEEESPLog EQU	-84
	XDEF	_LVOIEEESPPow
_LVOIEEESPPow EQU	-90
	XDEF	_LVOIEEESPSqrt
_LVOIEEESPSqrt EQU	-96
	XDEF	_LVOIEEESPTieee
_LVOIEEESPTieee EQU	-102
	XDEF	_LVOIEEESPFieee
_LVOIEEESPFieee EQU	-108
	XDEF	_LVOIEEESPAsin
_LVOIEEESPAsin EQU	-114
	XDEF	_LVOIEEESPAcos
_LVOIEEESPAcos EQU	-120
	XDEF	_LVOIEEESPLog10
_LVOIEEESPLog10 EQU	-126
	END
