*** DO NOT EDIT: FILE BUILT AUTOMATICALLY
*** mathtrans_lib.asm function offsets
	IDNT	mathtrans_LVO
	SECTION	mathtrans_LVO0
	XDEF	_LVOSPAtan
_LVOSPAtan EQU	-30
	XDEF	_LVOSPSin
_LVOSPSin EQU	-36
	XDEF	_LVOSPCos
_LVOSPCos EQU	-42
	XDEF	_LVOSPTan
_LVOSPTan EQU	-48
	XDEF	_LVOSPSincos
_LVOSPSincos EQU	-54
	XDEF	_LVOSPSinh
_LVOSPSinh EQU	-60
	XDEF	_LVOSPCosh
_LVOSPCosh EQU	-66
	XDEF	_LVOSPTanh
_LVOSPTanh EQU	-72
	XDEF	_LVOSPExp
_LVOSPExp EQU	-78
	XDEF	_LVOSPLog
_LVOSPLog EQU	-84
	XDEF	_LVOSPPow
_LVOSPPow EQU	-90
	XDEF	_LVOSPSqrt
_LVOSPSqrt EQU	-96
	XDEF	_LVOSPTieee
_LVOSPTieee EQU	-102
	XDEF	_LVOSPFieee
_LVOSPFieee EQU	-108
	XDEF	_LVOSPAsin
_LVOSPAsin EQU	-114
	XDEF	_LVOSPAcos
_LVOSPAcos EQU	-120
	XDEF	_LVOSPLog10
_LVOSPLog10 EQU	-126
	END
