*** DO NOT EDIT: FILE BUILT AUTOMATICALLY
*** mathieeedoubtrans_lib.asm function offsets
	IDNT	mathieeedoubtrans_LVO
	SECTION	mathieeedoubtrans_LVO0
	XDEF	_LVOIEEEDPAtan
_LVOIEEEDPAtan EQU	-30
	XDEF	_LVOIEEEDPSin
_LVOIEEEDPSin EQU	-36
	XDEF	_LVOIEEEDPCos
_LVOIEEEDPCos EQU	-42
	XDEF	_LVOIEEEDPTan
_LVOIEEEDPTan EQU	-48
	XDEF	_LVOIEEEDPSincos
_LVOIEEEDPSincos EQU	-54
	XDEF	_LVOIEEEDPSinh
_LVOIEEEDPSinh EQU	-60
	XDEF	_LVOIEEEDPCosh
_LVOIEEEDPCosh EQU	-66
	XDEF	_LVOIEEEDPTanh
_LVOIEEEDPTanh EQU	-72
	XDEF	_LVOIEEEDPExp
_LVOIEEEDPExp EQU	-78
	XDEF	_LVOIEEEDPLog
_LVOIEEEDPLog EQU	-84
	XDEF	_LVOIEEEDPPow
_LVOIEEEDPPow EQU	-90
	XDEF	_LVOIEEEDPSqrt
_LVOIEEEDPSqrt EQU	-96
	XDEF	_LVOIEEEDPTieee
_LVOIEEEDPTieee EQU	-102
	XDEF	_LVOIEEEDPFieee
_LVOIEEEDPFieee EQU	-108
	XDEF	_LVOIEEEDPAsin
_LVOIEEEDPAsin EQU	-114
	XDEF	_LVOIEEEDPAcos
_LVOIEEEDPAcos EQU	-120
	XDEF	_LVOIEEEDPLog10
_LVOIEEEDPLog10 EQU	-126
	END
