#define io_complete		1
#define scatter_dma		2
#define sync_received		3
#define modify_pointer_fetched	4
#define unusual_message_in	5
#define extended_not_len_3	6
#define extended_not_sync	7
#define target_rejected_msg	8
#define data_eaten		9
#define unknown_phase		10
#define no_msg_after_status	11
#define not_command_complete	12
#define bad_reselect		13
#define bad_address		14
#define selected_as_target	15
#define big_error_1		16
#define big_error_2		17
#define reselect_during_select	18
#define target_disconnect	19
#define ready_to_wait		20

#define in_phase	21
