##########################################################################

MAKEFILE=	Makefile
MAKEMETA=	/usr/commodore/amiga/V37/tools/makemeta
SRCDIRPATH=	workbench/fonts/helvetica
SRCDIR=		13
SUBSYSNAME=	13
DISKPATH=	fonts/helvetica/13

AFILES=		13.asm
OFILES=		13.obj

all:		${SUBSYSNAME}.ld

.INCLUDE=${MAKEMETA}
SYMBOLOPT=
