;
;
extrn	AB_Cyl:word
extrn	AB_Head:word
extrn	AB_Sec:word
extrn	AB_Secs:word
extrn	AB_SecsDone:word
extrn	AB_bill_int13:dword
extrn	AB_jparmseg:word
extrn	AB_jparmoff:word
extrn	AB_jbuffseg:word
extrn	AB_jbuffoff:word
extrn	AB_dataseg:word
extrn	AB_dataoff:word
extrn	AB_FileOpen:word
extrn	AB_NumHeads:word
extrn	AB_TrackSecs:word
extrn	AB_Cyls:word
extrn	AB_billmsg0:byte
extrn	AB_billmsg1:byte
extrn	AB_billmsg2:byte
extrn	AB_billmsg3:byte
extrn	AB_billmsg4:byte
extrn	AB_billmsg5:byte
extrn	AB_READPARMS:byte
extrn	AB_COPENFAILMSG:byte
extrn	AB_OPENFAILMSG:byte
extrn	AB_FTEXITMSG:byte
extrn	AB_File:word
extrn	AB_TFile:word
extrn	AB_FileName:byte
extrn	AB_okflag:word


