##########################################################################

MAKEFILE=	Makefile
MAKEMETA=	/usr/commodore/amiga/V37/tools/makemeta
SRCDIRPATH=	workbench/fonts/sapphire
SRCDIR=		14
SUBSYSNAME=	14
DISKPATH=	fonts/sapphire/14

AFILES=		14.asm
OFILES=		14.obj

all:		${SUBSYSNAME}.ld

.INCLUDE=${MAKEMETA}
SYMBOLOPT=
