CC	= cl
CF	= /AL /c /Otil /Za /Zi
AS	= masm
ASF     =  /ZI
LN  	= e:\mbin\link
LF	= /CO

atime.obj : atime.c
	$(CC) $(CF) atime.c

atime.exe : atime.obj
	$(LN) $(LF) atime, ,NUL.MAP , ljanus ;

