######################################################################
#
# This is now Amiga built
#
#MAKEMETA=	/usr/commodore/amiga/V${VERSION}/tools/makemeta
#
#SRCDIRPATH=	kickstart
#SRCDIR=		wbtag
#SUBSYSNAME=	wbtag
#MAKEFILE=	Makefile
#
#INTERNHFILES=	wbtag.h
#HFILES=		${INTERNHFILES}
#INTERNIFILES=	wbtag.i
#IFILES=		${INTERNIFILES}
#
#AFILES=		wbtag.asm
#
#FIRSTO=		wbtag.obj
#
#all:		${SUBSYSNAME}.ld
#		rm -f wbtag_rev.h
#
#doc:
#		rm -f ${SUBSYSNAME}.cat ${SUBSYSNAME}.doc
#
#.INCLUDE=${MAKEMETA}
