makedir janus
download /usr2/users/dieter/janus/janus/abs.asm janus/abs.asm
download /usr2/users/dieter/janus/janus/alloc.asm janus/alloc.asm
download /usr2/users/dieter/janus/janus/amigarw.asm janus/amigarw.asm
download /usr2/users/dieter/janus/janus/asmsupp.i janus/asmsupp.i
download /usr2/users/dieter/janus/janus/assembly.i janus/assembly.i
download /usr2/users/dieter/janus/janus/defs.asm janus/defs.asm
download /usr2/users/dieter/janus/janus/endcode.asm janus/endcode.asm
download /usr2/users/dieter/janus/janus/i86block.i janus/i86block.i
download /usr2/users/dieter/janus/janus/init.asm janus/init.asm
download /usr2/users/dieter/janus/janus/ints.asm janus/ints.asm
download /usr2/users/dieter/janus/janus/janus.i janus/janus.i
download /usr2/users/dieter/janus/janus/janusreg.i janus/janusreg.i
download /usr2/users/dieter/janus/janus/janusvar.i janus/janusvar.i
download /usr2/users/dieter/janus/janus/jfuncs.i janus/jfuncs.i
download /usr2/users/dieter/janus/janus/lib.asm janus/lib.asm
download /usr2/users/dieter/janus/janus/linkage.asm janus/linkage.asm
download /usr2/users/dieter/janus/janus/lvos.asm janus/lvos.asm
download /usr2/users/dieter/janus/janus/memrw.i janus/memrw.i
download /usr2/users/dieter/janus/janus/process.asm janus/process.asm
download /usr2/users/dieter/janus/janus/services.i janus/services.i
download /usr2/users/dieter/janus/janus/setupsig.i janus/setupsig.i
echo "Janus download completed"

makedir jdisk
download /usr2/users/dieter/janus/jdisk/abs.asm jdisk/abs.asm
download /usr2/users/dieter/janus/jdisk/asmsupp.i jdisk/asmsupp.i
download /usr2/users/dieter/janus/jdisk/assembly.i jdisk/assembly.i
download /usr2/users/dieter/janus/jdisk/beginio.asm jdisk/beginio.asm
download /usr2/users/dieter/janus/jdisk/cmds.asm jdisk/cmds.asm
download /usr2/users/dieter/janus/jdisk/cmdt.asm jdisk/cmdt.asm
download /usr2/users/dieter/janus/jdisk/dev.asm jdisk/dev.asm
download /usr2/users/dieter/janus/jdisk/djmount.asm jdisk/djmount.asm
download /usr2/users/dieter/janus/jdisk/djmount.i jdisk/djmount.i
download /usr2/users/dieter/janus/jdisk/endcode.asm jdisk/endcode.asm
download /usr2/users/dieter/janus/jdisk/init.asm jdisk/init.asm
download /usr2/users/dieter/janus/jdisk/jddata.i jdisk/jddata.i
echo "Jdisk download complete"

makedir lp1
download /usr2/users/dieter/janus/lp1/asmsupp.i lp1/asmsupp.i
download /usr2/users/dieter/janus/lp1/assembly.i lp1/assembly.i
download /usr2/users/dieter/janus/lp1/parallel.asm lp1/parallel.asm
echo "Lp1 download completed"

makedir pchand
download /usr2/users/dieter/janus/pchand/diagmsg.i pchand/diagmsg.i
download /usr2/users/dieter/janus/pchand/handler.asm pchand/handler.asm
download /usr2/users/dieter/janus/pchand/kdiag.asm pchand/kdiag.asm
download /usr2/users/dieter/janus/pchand/macros.i pchand/macros.i
echo "Pchand download completed"

