CC	= cl
CF	= /AL /c /FoOBJ\ /Otil /Za /Zi
AS	= masm
ASF     =  /ZI
LN  	= link
LF	= /CO

OBJ\ex2.obj : ex2.c
	$(CC) $(CF) ex2.c

ex2.exe : OBJ\ex2.obj
	$(LN) $(LF) OBJ\ex2, ,NUL.MAP , ljanus ;

