€ˆRESOURCES_MISC_H€RESOURCES_MISC_HˆEXEC_TYPES_HŒ"exec/types.h"‡ˆEXEC_LIBRARIES_HŒ"exec/libraries.h"‡€MR_SERIALPORT 0€MR_SERIALBITS 1€MR_PARALLELPORT 2€MR_PARALLELBITS 3€NUMMRTYPES 4
ƒMiscResource{
ƒLibrary mr_Library;
—mr_AllocArray[NUMMRTYPES];
};€MR_ALLOCMISCRESOURCE (LIB_BASE)€MR_FREEMISCRESOURCE (LIB_BASE+LIB_VECSIZE)€MISCNAME "misc.resource"‡