
/* Include file generated by Toolmaker V1.1.19 */

/* Text */
 
#define TEXT_W0TITLE	"NIPC Network Information"
#define TEXT_W0G2	""
#define TEXT_W0G2L1S1	"Query"
#define TEXT_W0G2L1S2	"Match"
#define TEXT_W0G3	""
#define TEXT_W0G3L1S1	"Query"
#define TEXT_W0G3L1S2	"Match"
#define TEXT_W0G4	""
#define TEXT_W0G4L1S1	"Query"
#define TEXT_W0G4L1S2	"Match"
#define TEXT_W0G5	""
#define TEXT_W0G5L1S1	"Query"
#define TEXT_W0G5L1S2	"Match"
#define TEXT_W0G6	""
#define TEXT_W0G7	"Realm"
#define TEXT_W0G8	"Host"
#define TEXT_W0G9	"Entity"
#define TEXT_W0G10	"Service"
#define TEXT_W0G11	"System Info"
#define TEXT_W0G12	"Owner"
#define TEXT_W0G13	"Description"
#define TEXT_W0G14	"IP Address"
#define TEXT_W0G15	"Max Responses"
#define TEXT_W0G16	"Timeout"
#define TEXT_W0G17	"Send Inquiry"
#define TEXT_W0G18	""
#define TEXT_W0G18L1S1	"Query"
#define TEXT_W0G18L1S2	"Match"

