
/* Include file generated by Toolmaker V1.1.19 */

/* TMWindowInfo structure */
 
struct TMWindowInfo
  {
  struct Window *Window;	/* pointer to Window structure */
  struct Menu *Menu;	/* pointer to Menu structure */
  struct Requester Requester;	/* Requester structure for DISABLE/ENABLE */
  UBYTE DisableCount;	/* Count for nested DISABLE/ENABLEs */
  ULONG Flags;	/* TMWF_ flags */
  struct Gadget **FirstGadget;	/* pointer to gadget array */
  APTR UserData;
  };

/* TMData structure */
 
struct TMData
  {
  ULONG Size;	/* Size of TMData structure */
  struct MsgPort *WindowMsgPort;	/* pointer to window message port */
  ULONG UserSignal;	/* User signal flag for Wait */
  LONG ReturnCode;	/* Return code for exit() */
  struct Screen     *Screen;	/* pointer to Screen structure */
  struct VisualInfo *VisualInfo;	/* pointer to VisualInfo structure */
  struct Gadget *Window0Gadget[19];	/* Gadget structure array */
  struct TMWindowInfo TMWindowInfo[1];	/* TMWindowInfo structure array */
  APTR UserData;
  };

/* Function Prototypes */
 
LONG TM_Request(struct Window *, char *, char *, char *);
LONG TM_Open(struct TMData **);
VOID TM_Close(struct TMData *);
VOID TM_EventLoop(struct TMData *);
VOID TM_RemoveWindow(struct TMWindowInfo *);
BOOL TM_WindowSignal(struct TMData *);
BOOL UserSignal(struct TMData *, ULONG);
BOOL TM_Window0(struct TMData *, UBYTE);
BOOL TM_Window0IDCMP(struct TMData *, struct IntuiMessage *);
BOOL Window0GADGETDOWN(struct TMData *, struct IntuiMessage *);
BOOL Window0GADGETUP(struct TMData *, struct IntuiMessage *);
BOOL Window0CLOSEWINDOW(struct TMData *, struct IntuiMessage *);

/* Global Data */
 
extern struct Library *IntuitionBase, *GadToolsBase;
extern UWORD chip WaitPointer[];

/* General constants */
 
#define DISPLAY  1	/* Window function argument */
#define REMOVE   2	/* Window function argument */
#define DISABLE  3	/* Window function argument */
#define ENABLE   4	/* Window function argument */

#define TMERROR_NONE       0	/* Success */
#define TMERROR_MEMORY     1	/* AllocMem error */
#define TMERROR_MSGPORT    2	/* CreateMsgPort error */
#define TMERROR_SCREEN     3	/* OpenScreen/LockPubScreen error */
#define TMERROR_VISUALINFO 4	/* GetVisualInfo error */

#define TMWF_OPEN     0x00000001	/* Window control */
#define TMWF_DISABLED 0x00000002	/* Window disabled */

#define TITLEBARHEIGHT (TMData->Screen->BarHeight)	/* Height of title bar */

/* Window, Menu, and Gadget pointers */
 
#define window_IQ_WINDOW	TMData->TMWindowInfo[0].Window	/* Window pointer */
#define gadget_REALM_TYPE	TMData->Window0Gadget[2]	/* Gadget pointer */
#define gadget_HOST_TYPE	TMData->Window0Gadget[3]	/* Gadget pointer */
#define gadget_ENTITY_TYPE	TMData->Window0Gadget[4]	/* Gadget pointer */
#define gadget_SVC_TYPE	TMData->Window0Gadget[5]	/* Gadget pointer */
#define gadget_RESULT_DISP	TMData->Window0Gadget[6]	/* Gadget pointer */
#define gadget_REALM_NAME	TMData->Window0Gadget[7]	/* Gadget pointer */
#define gadget_HOST_NAME	TMData->Window0Gadget[8]	/* Gadget pointer */
#define gadget_ENTITY_NAME	TMData->Window0Gadget[9]	/* Gadget pointer */
#define gadget_SVC_NAME	TMData->Window0Gadget[10]	/* Gadget pointer */
#define gadget_SYS_INFO	TMData->Window0Gadget[11]	/* Gadget pointer */
#define gadget_OWNER_NAME	TMData->Window0Gadget[12]	/* Gadget pointer */
#define gadget_MACH_DESC	TMData->Window0Gadget[13]	/* Gadget pointer */
#define gadget_IP_STR	TMData->Window0Gadget[14]	/* Gadget pointer */
#define gadget_MAX_RESP	TMData->Window0Gadget[15]	/* Gadget pointer */
#define gadget_MAX_TIME	TMData->Window0Gadget[16]	/* Gadget pointer */
#define gadget_DO_INQUIRY	TMData->Window0Gadget[17]	/* Gadget pointer */
#define gadget_IP_TYPE	TMData->Window0Gadget[18]	/* Gadget pointer */

/* Gadget IDs */
 
#define ID_REALM_TYPE	1	/* Gadget ID */
#define ID_HOST_TYPE	2	/* Gadget ID */
#define ID_ENTITY_TYPE	3	/* Gadget ID */
#define ID_SVC_TYPE	4	/* Gadget ID */
#define ID_RESULT_DISP	5	/* Gadget ID */
#define ID_REALM_NAME	6	/* Gadget ID */
#define ID_HOST_NAME	7	/* Gadget ID */
#define ID_ENTITY_NAME	8	/* Gadget ID */
#define ID_SVC_NAME	9	/* Gadget ID */
#define ID_SYS_INFO	10	/* Gadget ID */
#define ID_OWNER_NAME	11	/* Gadget ID */
#define ID_MACH_DESC	12	/* Gadget ID */
#define ID_IP_STR	13	/* Gadget ID */
#define ID_MAX_RESP	14	/* Gadget ID */
#define ID_MAX_TIME	15	/* Gadget ID */
#define ID_DO_INQUIRY	16	/* Gadget ID */
#define ID_IP_TYPE	17	/* Gadget ID */

/* Menu, item, and subitem numbers */
 

/* Functions */
 
#define Window_IQ_WINDOW	TM_Window0	/* Window function */
#define Window_IQ_WINDOW_GADGETDOWN	Window0GADGETDOWN	/* GADGETDOWN IDCMP function */
#define Window_IQ_WINDOW_GADGETUP	Window0GADGETUP	/* GADGETUP IDCMP function */
#define Window_IQ_WINDOW_CLOSEWINDOW	Window0CLOSEWINDOW	/* CLOSEWINDOW IDCMP function */

/* WindowInfo pointers */
 
#define WindowInfo_IQ_WINDOW	TMData->TMWindowInfo[0]	/* WindowInfo structure pointer */

