##########################################################################

MAKEFILE=	Makefile
MAKEMETA=	/usr/commodore/amiga/V37/tools/makemeta
SRCDIRPATH=	workbench/fonts/opal
SRCDIR=		12
SUBSYSNAME=	12
DISKPATH=	fonts/opal/12

AFILES=		12.asm
OFILES=		12.obj

all:		${SUBSYSNAME}.ld

.INCLUDE=${MAKEMETA}
SYMBOLOPT=
