##########################################################################

MAKEFILE=	Makefile
MAKEMETA=	/usr/commodore/amiga/V37/tools/makemeta
SRCDIRPATH=	workbench/fonts/times
SRCDIR=		15
SUBSYSNAME=	15
DISKPATH=	fonts/times/15

AFILES=		15.asm
OFILES=		15.obj

all:		${SUBSYSNAME}.ld

.INCLUDE=${MAKEMETA}
SYMBOLOPT=
