######################################################################

MAKEMETA=	/usr/commodore/amiga/V36/tools/makemeta

MAKEFILE=	Makefile
SRCDIRPATH=	workbench/l
SRCDIR=		aux-handler
SUBSYSNAME=	aux-handler

BFILES=		aux-handler.b

#STARTUP=	${LIBDIR}/bcpl-startup.obj
OFILES=		aux-handler.obj

all:		${SUBSYSNAME}.ld

.INCLUDE=${MAKEMETA}
