#pragma libcall AppShellBase HandleApp       1e           981004
#pragma libcall AppShellBase HandleAppAsync  24             1002
#pragma libcall AppShellBase HandlerFuncA    2a             1002
#pragma libcall AppShellBase HandlerDataA    30             1002
#pragma libcall AppShellBase GetText         36           981004
#pragma libcall AppShellBase PrepText        3c           981004
#pragma libcall AppShellBase ParseLine       42             1002
#pragma libcall AppShellBase BuildParseLine  48            81003
#pragma libcall AppShellBase FreeParseLine   4e              001
#pragma libcall AppShellBase FindType        54            81003
#pragma libcall AppShellBase MatchValue      5a             1002
#pragma libcall AppShellBase QStrCmpI        60             1002
#pragma libcall AppShellBase RemoveMsgPort   66              001
#pragma libcall AppShellBase NotifyUser      6c            81003
#pragma libcall AppShellBase APSHSetWaitPointer 72             1002
#pragma libcall AppShellBase APSHClearPointer 78             1002
#pragma libcall AppShellBase PerfFunc        7e           981004
#pragma libcall AppShellBase FindNameI       84             9802
#pragma libcall AppShellBase AddFuncEntry    8a             1002
#pragma libcall AppShellBase FreeFuncEntry   90             1002
#pragma libcall AppShellBase AddFuncEntries  96             1002
#pragma libcall AppShellBase FreeFuncEntries 9c              001
#pragma libcall AppShellBase GetFuncEntry    a2            81003
#pragma libcall AppShellBase GetFuncID       a8             1002
#pragma libcall AppShellBase GetFuncName     ae             1002
#pragma libcall AppShellBase GetBaseInfo     b4           981004
#pragma libcall AppShellBase NewProject      ba            81003
#pragma libcall AppShellBase RenumProjects   c0            81003
#pragma libcall AppShellBase RemoveProject   c6            81003
#pragma libcall AppShellBase AddProjects     cc           981004
#pragma libcall AppShellBase FreeProject     d2              001
#pragma libcall AppShellBase FreeProjects    d8             1002
#pragma libcall AppShellBase GetProjNode     de            81003
#pragma libcall AppShellBase SwapProjNodes   e4           981004
#pragma libcall AppShellBase IconFromWBArg   ea              001
#pragma libcall AppShellBase setup_arexxA    f0             1002
#pragma libcall AppShellBase setup_dosA      f6             1002
#pragma libcall AppShellBase setup_idcmpA    fc             1002
#pragma libcall AppShellBase APSHGetGadgetInfo 102          2981005
#pragma libcall AppShellBase APSHGetWindowInfo 108            81003
#pragma libcall AppShellBase setup_sipcA     10e             1002
#pragma libcall AppShellBase SendSIPCMessage 114            81003
#pragma libcall AppShellBase SendSIPCMessageP 11a           981004
#pragma libcall AppShellBase OpenSIPC        120            81003
#pragma libcall AppShellBase CloseSIPC       126             1002
#pragma libcall AppShellBase setup_toolA     12c             1002
#pragma libcall AppShellBase setup_wbA       132             1002
#pragma libcall AppShellBase LMatchFirst     138            81003
#pragma libcall AppShellBase LMatchNext      13e              001
#pragma libcall AppShellBase LMatchEnd       144              001
#pragma libcall AppShellBase LockAppInfo     14a              901
#pragma libcall AppShellBase UnlockAppInfo   150              001
#pragma libcall AppShellBase ExpandPattern   156            BA903
#pragma libcall AppShellBase UpdateProject   15c            BA903
#pragma libcall AppShellBase APSHSignal      162             0902
#pragma libcall AppShellBase NewAPSHObject   168            90803
#pragma libcall AppShellBase DisposeAPSHObject 16e             9802
#pragma libcall AppShellBase SetAPSHAttr     174            A9803
#pragma libcall AppShellBase GetAPSHAttr     17a           A90804
