
	FUNCDEF SetJanusHandler
	FUNCDEF SetJanusEnable
	FUNCDEF SetJanusRequest
	FUNCDEF SendJanusInt
	FUNCDEF CheckJanusInt
	FUNCDEF AllocJanusMem
	FUNCDEF FreeJanusMem
	FUNCDEF JanusMemBase
	FUNCDEF JanusMemType
	FUNCDEF JanusMemToOffset
	FUNCDEF GetParamOffset
	FUNCDEF SetParamOffset
	FUNCDEF GetJanusStart
	FUNCDEF SetupJanusSig
	FUNCDEF CleanupJanusSig
	FUNCDEF JanusLock
	FUNCDEF JanusUnlock
	FUNCDEF JBCopy
