#ifndef	ENVOY_ACCOUNTSINTERNAL_H
#define ENVOY_ACCOUNTSINTERNAL_H

/* Error codes for the security server */

#define	ACCERROR_NORESOURCES	100
#define ACCERROR_NOPRIVS	101
#define ACCERROR_NOAUTHORITY	102
#define ACCERROR_GROUPEXISTS	108
#define ACCERROR_NOFREEGROUPS	109

#endif	/* ENVOY_ACCOUNTSINTERNAL_H */
