##########################################################################
# $Id: Makefile,v 36.1 90/11/30 15:45:36 eric Exp $
#

MAKEMETA=	/usr/commodore/amiga/V${VERSION}/tools/makemeta

MAKEFILE=	Makefile
SRCDIRPATH=	include

# master makefile script for include parts
SUBDIRS=	clib devices hardware resources

all:		${SUBDIRS}

.INCLUDE=${MAKEMETA}
