;*************************************************************************
; (PC side file)
;
; janus.inc -- Include all other janus include files
;
; Copyright (c) 1986, Commodore Amiga Inc.,  All rights reserved.
;
; 7-15-88 - Bill Koester - Created this file
; 7-26-88 - Bill Koester - Added ServMac.inc
;*************************************************************************

include  janus/janusvar.inc
include  janus/memory.inc
include  janus/memrw.inc
include  janus/harddisk.inc
include  janus/services.inc
include  janus/syscall.inc
include  janus/pcdisk.inc
include  janus/timeserv.inc
include  janus/servmac.inc

