##########################################################################

MAKEFILE=	Makefile
MAKEMETA=	/usr/commodore/amiga/V37/tools/makemeta
SRCDIRPATH=	workbench/fonts/emerald
SRCDIR=		17
SUBSYSNAME=	17
DISKPATH=	fonts/emerald/17

AFILES=		17.asm
OFILES=		17.obj

all:		${SUBSYSNAME}.ld

.INCLUDE=${MAKEMETA}
SYMBOLOPT=
