#!/bin/csh -f

set sourced=/batgirl/pub/src/wack

echo buck-star $*

if ( $#argv == 0 ) then
    set args = $sourced/RCS/showi.c,v
else
    set args = ($*)
endif

echo $args

foreach file ($args)
    set local=`basename $file ,v`
    set base=$local:r
    set file = $sourced/RCS/$local,v

    echo rcsfile: $file
    echo local file: $local
    echo base name: $base
end
