CC	= cl
CF	= /AL /c /FoOBJ\ /Otil /Za /Zi
AS	= masm
ASF     =  /ZI
LN  	= link
LF	= /CO

OBJ\ex7.obj : ex7.c
	$(CC) $(CF) ex7.c

ex7.exe : OBJ\ex7.obj
	$(LN) $(LF) OBJ\ex7, ,NUL.MAP , ljanus ;

