    "Intellifont\256\n"
    "\n"
    "Welcome to Intellifont Help.  This is the initial help box.\n"
    "Cycle through the different help boxes by selecting inside\n"
    "the help box.  Receive a reminder about how a specific item\n"
    "works by clicking outside the help box in the area of that\n"
    "item.  Help boxes are displayed opposite the item being\n"
    "described.\n"
    "\n"
    "Intellifont is used to manage the installation of Intellifont\n"
    "outline fonts onto your Amiga.\n"
    "\n"
    "Press Esc to exit Help.  Select here or on a specific item\n"
    "to continue.",

    "Outline Font Source\n"
    "\n"
    "This field specifies the source directory that contains\n"
    "Intellifont outline typefaces.  Intellifont understands two\n"
    "typeface formats.  The first is a Compugraphic font disk already\n"
    "formatted for the Amiga, such as a CG Fonts disk from Gold Disk.\n"
    "The second is an MS-DOS FAIS disk not yet formatted for the Amiga,\n"
    "such as a TypeDirector font disk from Agfa Compugraphic.  Using an\n"
    "MS-DOS disk directly requires an MS-DOS handler, such as CrossDOS.\n"
    "\n"
    "The little file folder button invokes the standard file requester\n"
    "for directory selection.  Only directories are displayed, and only\n"
    "the directory field of the file requester is used by Intellifont.\n"
    "\n"
    "Press Esc to exit Help.  Select to continue.",

    "Source Typefaces\n"
    "\n"
    "This list contains the Intellifont\n"
    "typefaces found in the Outline Font\n"
    "Source.  Select entries on this list\n"
    "to mark them for installation with a\n"
    "plus (+) in the left column.  Select\n"
    "a marked entry to remove the mark.\n"
    "\n"
    "Intellifont typeface names on the\n"
    "Amiga are those specified by the\n"
    "typeface vendor, with spaces\n"
    "removed.  They cannot be changed.\n"
    "\n"
    "Press Esc to exit Help.  Select to\n"
    "continue.",

    "Install Marked Typefaces\n"
    "\n"
    "Selecting this button initiates the installation of all the marked\n"
    "Source Typefaces into the Destination Font Drawer.  Included in\n"
    "this installation process is a list of standard sizes to be used by\n"
    "applications when presenting their font selection menus.  These\n"
    "sizes are taken from the environment text file ENV:sys/Intellifont,\n"
    "if it exists.  You must exit Intellifont to change this file.\n"
    "\n"
    "Technical Note: Installation creates three files for each typeface\n"
    "installed:  <name>.font, <name>.otag, and\n"
    "_Bullet_Outlines/<name>.type\n"
    "\n"
    "Press Esc to exit Help.  Select to continue.",

    "Destination Font Drawer\n"
    "\n"
    "This field specifies the destination directory to install the\n"
    "outline typefaces into.  It is intended that this directory be an\n"
    "element of the Fonts: assign path.  The Fonts: Path Component\n"
    "button makes it easy to select such directories.\n"
    "\n"
    "Other directories are allowed.  Typefaces installed there would not\n"
    "be accessable by most applications.  Using a non-Fonts: directory\n"
    "is appropriate if Intellifont is being used to generate Amiga\n"
    "bitmap fonts for a 1.3 environment.\n"
    "\n"
    "The button with the file folder icon brings up the standard file\n"
    "requester to assist in directory selection.\n"
    "\n"
    "Press Esc to exit Help.  Select to continue.",

    "Existing Fonts & Typefaces\n"
    "\n"
    "This list shows all the Amiga fonts\n"
    "and Intellifont outline typefaces\n"
    "already existing in the Destination\n"
    "Font Drawer.  Intellifont typefaces\n"
    "are indicated by a bullet (\267).\n"
    "If the name of an existing Amiga\n"
    "font conflicts with an Intellifont\n"
    "typeface to be installed, the Amiga\n"
    "font must be renamed.  Exit\n"
    "Intellifont, rename the Amiga font\n"
    "directory, and invoke FixFonts.\n"
    "\n"
    "Press Esc to exit Help.  Select to\n"
    "continue.",

    "Modify Existing Typefaces\n"
    "\n"
    "This button enters the Intellifont Modify window where outline\n"
    "typeface modification and deletion for typefaces in this directory\n"
    "can be performed.  Intellifont installs typefaces with standard\n"
    "characteristics taken from the ENV: files sys/Intellifont and\n"
    "sys/Diskfont.  The Intellifont Modify window is the right place to\n"
    "modify the sizes for a particular typeface.  The environment\n"
    "variable ENV:sys/Intellifont is the right place modify the sizes\n"
    "for all future installations.\n"
    "\n"
    "Intellifont Modify has its own help messages to describe its use.\n"
    "\n"
    "Select here or press Esc to exit Help.  Select on a specific item\n"
    "to continue.",

    "Intellifont Modify\n"
    "\n"
    "This window allows the inspection and modification of\n"
    "outline typefaces.  Amiga applications usually present a\n"
    "font menu to the user containing only those fonts and sizes\n"
    "that are installed.  It asks the system (via the diskfont\n"
    "library) for this information.  For outline typefaces, the\n"
    "sizes available are arbitrary.  This window provides a way\n"
    "to specify which sizes to tell applications about.\n"
    "\n"
    "Also, for often-used sizes, an Amiga bitmap form of the\n"
    "font can be created.  This takes more disk space, but is\n"
    "quicker to load than creating a font size from its\n"
    "outline.\n"
    "\n"
    "Press Esc to exit Help.  Select to continue.",

    "Existing Outline Typefaces\n"
    "\n"
    "The outline typeface whose Size &\n"
    "Bitmap is displayed is selected from\n"
    "this list.  The active entry is\n"
    "reflected at the bottom of the\n"
    "list.  The font drawer containing\n"
    "these outline typefaces is displayed\n"
    "here, but it cannot be changed\n"
    "here.  It must be changed in the\n"
    "main Intellifont window.\n"
    "\n"
    "Press Esc to exit Help.  Select to\n"
    "continue.",

    "Delete Typeface\n"
    "\n"
    "Selecting this button marks the\n"
    "active typeface for deletion and\n"
    "removes it from the typeface list.\n"
    "It is not actually deleted until\n"
    "Perform Changes is selected, so the\n"
    "deletion can be aborted by selecting\n"
    "Cancel.\n"
    "\n"
    "Press Esc to exit Help.  Select to\n"
    "continue.",

    "Perform Changes\n"
    "\n"
    "This button causes all the changes made in this window to actually\n"
    "be performed, updating the files in the destination directory.\n"
    "\n"
    "To return to the main Intellifont window after performing a set of\n"
    "changes, select Cancel.\n"
    "\n"
    "Press Esc to exit Help.  Select to continue.",

    "Size & Bitmap\n"
    "\n"
    "This lists font sizes (for appli-\n"
    "cation inquiry) and which of them\n"
    "have Amiga bitmap disk images.\n"
    "The size field at the bottom is the\n"
    "active size.  Press S to activate\n"
    "it.  Change it to add a new size.\n"
    "\n"
    "The size is the pixel height from\n"
    "the highest accent to the lowest\n"
    "descender.  A typical capital letter\n"
    "height is 1/2 to 2/3 of this.\n"
    "\n"
    "Press Esc to exit Help.  Select to\n"
    "continue.",

    "Size & Bitmap Modification\n"
    "\n"
    "Add Size adds the active size to the\n"
    "list.  Delete Size deletes it.\n"
    "Create Bitmap ensures an Amiga\n"
    "bitmap font exists for the active\n"
    "size.  Delete Bitmap ensures no\n"
    "bitmap exists.  Press the underlined\n"
    "character as a keyboard shortcut.\n"
    "\n"
    "An Amiga bitmap takes disk space,\n"
    "but is quicker to load.  Create them\n"
    "for often-used smaller sizes.\n"
    "\n"
    "Press Esc to exit Help.  Select to\n"
    "continue.",

    "Cancel\n"
    "\n"
    "This button returns to the main Intellifont window without\n"
    "performing any further changes.\n"
    "\n"
    "Select here or press Esc to exit Help.  Select on a specific item\n"
    "to continue.",

