*	ioffsets.i --
*	automatically generated by offsets.c
ib_sizeof	equ	$c4e
	xdef	_SysBaseOffset
_SysBaseOffset	equ	$564
	xdef	_GfxBaseOffset
_GfxBaseOffset	equ	$568
	xdef	_LayersBaseOffset
_LayersBaseOffset	equ	$56c
	xdef	_UtilityBaseOffset
_UtilityBaseOffset	equ	$570
	xdef	_KeymapBaseOffset
_KeymapBaseOffset	equ	$574

*	offset to semaphores: $822
*	view offset: $76
