
/* Text include file generated by Toolmaker V1.19 */

#define WINDOWTEXT_GFXDATAB	"Gfx DataBase Browser"
#define GADGETTEXT_PRINT	"_Print"
#define GADGETTEXT_MODEIDS	"ModeIDs"
#define GTLV_Labels_MODEIDS_THIRD	"third"
#define GADGETTEXT_MODEID	"_ModeID"
#define GTST_String_MODEID	""
#define GADGETTEXT_NAME	"_Name"
#define GADGETTEXT_MONITOR	"M_onitor"
#define GADGETTEXT_DIMENSIO	"_Dimension"
#define GADGETTEXT_DISPLAY	"D_isplay"
#define GADGETTEXT_VECTOR	"_Vector"
#define GADGETTEXT_DATA	"D_ata"
#define GADGETTEXT_BESTMODE	"_BestModeIDAttrs"
#define GTST_String_BESTMODE	""

