.\" @(#)autodoc.man.1 1.00 8/21/89
.\"
.TH Autodoc 1L "August 21 1989"
.UC 4
.SH NAME
autodoc \- Extracts and sorts autodocs from the given files to stdout.
.SH SYNOPSIS
.B autodoc
[ -tnum ] [ -i ] [ -a ] [ -s ] [ -C ] [ -lnum ] [ -w ] [ -c ] [ -f ] 
[ -r ] [ -Ffile ] [ -I ] 
.B file1
 [
.B file2
] [...]
.SH DESCRIPTION
.B autodoc
extracts autodocs from files "file1", "file2", ... Sorts the output to 
stdout.
.PP
Options offered by
.B autodoc
are the following:
.TP 0.6i
.B -tnum
Convert tabs into num spaces.
.TP 0.6i
.B -i
Extract ONLY internal autodocs (autodocs that have an 'i' as the 6th character
in a line that begins an autodoc).
.TP 0.6i
.B -a
Process autodocs that begin with an asteric in the first column. Disable
C language autodocs (can be renabled with -C).
.TP 0.6i
.B -s
Process autodocs that begin with a semi colon in the first column. Disable
C language autdocs (can be renabled with -C).
.TP 0.6i
.B -C
Process C language autodocs (Default). Force processing of C
language autodocs when used with -a or -s.
.TP 0.6i
.B -lnum
Set the line length to num. (default = 78 chars).
.TP 0.6i
.B -w
Turn off word wrap. Lines longer than line length will be chopped.
.TP 0.6i
.B -c
Do not convert C comments. From backslash asteric to slash asteric. This
allows comments in autodocs without the need for nested comments.
.TP 0.6i
.B -f
Disable form feeds between autodoc entries.
.TP 0.6i
.B -r
Output autodocs in troff format (currently not implemented).
.TP 0.6i
.B -Ffile
Use the file 'file' as the temporary file. (default = tmpfile).
.TP 0.6i
.B -I
Do not include a TABLE Of CONTENTS as the first part of the output.
.SH USAGE
.PP
.B autodoc
sends formatted file to standard output. User could redirect this output
to a file or pipe it directly to a print command, like lpr in UNIX:

.ti +0.5i
autodoc file1 > file2

.ti +0.5i
autodoc file1 | lp

.PP
Ex. to extract ALL C language autodocs except internal autodocs and print
with a table of contents.

.ti +0.5i
autodoc file1 > outfile

.PP
Ex. to extract ONLY non-internal autodocs starting with a semicolon
and print with a table of contents.

.ti +0.5i
autodoc -s file1 > outfile

.PP
Ex. to extract ALL possible autodocs except internal autodocs and print
with a table of contents.

.ti +0.5i
autodoc -a -s -C file1 > outfile

.PP
.PP
This filter must be used only with text files.
.SH "SEE ALSO"
a2ps(1L) 
.SH AUTHOR
Bill Koester (bill@janus).
