
/* Include file generated by Toolmaker V1.1.22 */

/* Text */
 
#define TEXT_S0TITLE	"TestManager"
#define TEXT_W0TITLE	"Test Status"
#define TEXT_W0T1	"TestManager"
#define TEXT_W0G0	"Last ERROR from"
#define TEXT_W0G0T1	"                      N/A"
#define TEXT_W0G1	"Last Msg From"
#define TEXT_W0G1T1	"                      N/A"
#define TEXT_W0G2	"Error Count: "
#define TEXT_W0G2T1	"          0"
#define TEXT_W0G3	"Last ERROR Rec'd"
#define TEXT_W0G3T1	"                      N/A"
#define TEXT_W0G4	"Last MSG Rec'd"
#define TEXT_W0G4T1	"                      N/A"
#define TEXT_W0G5	""
#define TEXT_W0G5T1	"     PASS     "                         /* by hand */
#define TEXT_W0G5T2 "     FAIL     "                         /* by hand */
#define TEXT_W0G6	""
#define TEXT_W0G6T1	"   Testing    "                            /* by hand */
#define TEXT_W0G6T2 "  Idle/Done   "                            /* by hand */
#define TEXT_W0G7	"Abort Test"
#define TEXT_W0G8	"Exit"

