#! /bin/sh

goal="walk and archive 127 character directory tree"
bru=${BRU:-bru}

# Parse our args.  Options include:
#
#	-s	Print our one line test goal and quit
#

while true
do
	case $1 in
		-d)	dflag="on"
			shift
			;;
		-g)	echo $goal
			exit 0
			;;
		*bru*)	bru=$1
			shift
			;;
		*)	break
			;;
	esac
done

cat <<EOT
This test is intended to create a pathname that is the maximum that will
fit in the primary fname/lname fields in the block header fields.  Bru
should not complain about archiving or restoring the file.
EOT

if [ "$dflag" != "on" ]
then
	trap "../bin/rmtree tmpdir000 ; rm -f bru.out ; exit 1" 1 2 13 15
fi

# First clean up any stuff that may be left from a previous test.

if test -d tmpdir000
then
	../bin/rmtree tmpdir000
fi

if test -f bru.out
then
	rm -f bru.out
fi

# Run test.

top=`pwd`
for i in 00 01 02 03 04 05 06 07 08 09 10 11
do
	mkdir tmpdir0$i
	cd tmpdir0$i
done
touch abcdefg
cd $top

$bru -cvf bru.out tmpdir000
echo "bru exit status was $?"

$bru -ivf bru.out
echo "bru exit status was $?"

$bru -dddvf bru.out
echo "bru exit status was $?"

../bin/rmtree tmpdir000

$bru -xvf bru.out
echo "bru exit status was $?"

$bru -dddvf bru.out
echo "bru exit status was $?"

if [ "$dflag" != "on" ]
then
	../bin/rmtree tmpdir000
	rm -f bru.out
fi

exit 0




