;	prologue.h	
;	standard prologue for c86 assembly(large model)

;	DEFINE ARGUMENT BASE RELATIVE FROM BP

@AB	EQU	6

_TEXT	SEGMENT BYTE PUBLIC 'CODE'
_TEXT   ENDS
CONST 	SEGMENT WORD PUBLIC 'CONST'
CONST 	ENDS
_BSS  	SEGMENT WORD PUBLIC 'BSS'
_BSS 	ENDS
_DATA 	SEGMENT WORD PUBLIC 'DATA'
_DATA 	ENDS
DGROUP	GROUP	CONST,_BSS,_DATA
_TEXT	SEGMENT 
	ASSUME	CS:_TEXT,DS:DGROUP
;	ASSUME	CS:_TEXT,DS:DGROUP,SS:DGROUP,ES:DGROUP

;	END OF PROLOGUE.h
