/* ModuleOwners.h
 *
 */

struct ModuleOwners
{
    STRPTR mo_Module;
    STRPTR mo_Owners;
};

struct ModuleOwners mo[] =
{
    {"1.2","eric"},
    {"1.3","eric"},
    {"1.3.3","darren eric peter"},
    {"2.0","eric peter havemose"},
    {"A2024","spence chrisg havemose"},
    {"A2091.A590","steveb jesup andy"},
    {"A2065","bj dlarson gregm"},
    {"A2090.A2090A","jesup"},
    {"A2232","peter bryce"},
    {"A2300","hedley"},
    {"A2410","havemose"},
    {"A2620","daveh peter"},
    {"A2630","daveh peter"},
    {"A3000","hedley"},
    {"aa.chips","havemose chrisg spence raible bthomas lenthe"},
    {"addmonitor","spence chrisg havemose vertex"},
    {"AmigaBasic","carolyn"},
    {"amiga.lib","peter vertex jesup eric"},
    {"amigaguide","davidj"},
    {"amigaterm","peter"},
    {"amigavision","campbell cathy"},
    {"arexx","mks"},
    {"art","ross peter"},
    {"appshell","davidj"},
    {"as225","dlarson bj gregm"},
    {"asl.library","vertex"},
    {"audio.device","mks"},
    {"aug.command","eric peter"},
    {"autoconfig","mks"},
    {"autovecs","mks"},
    {"battclock","darren mks"},
    {"battmem","darren mks"},
    {"battcard","darren"},
    {"bindmonitor","spence chrisg havemose vertex"},
    {"blink","walker@dev.sas.com"},
    {"bootmenu","spence vertex"},
    {"bolt","dlarson gregm bj"},
    {"bridgeboard","havemose bill"},
    {"bru","eric"},
    {"bullet","kodiak darren havemose davidj"},
    {"cdos.command","eric vertex"},
    {"cdtv","carl andy hedley gail dong reichart rutgers!ucbvax!well!ewhac jerryh havemose"},
    {"cdtv.cr","havemose jerryh andy kaori jesup mikec jjszucs"},
    {"cia.resource","darren andy"},
    {"clipboard","darren"},
    {"commodities","vertex"},
    {"compatible","mks"},
    {"con-handler","jesup andy"},
    {"console.device","darren"},
    {"creditcard","darren"},
    {"crossdos","eric darren jesup"},
    {"custom.chips","lenthe"},
    {"datatypes","davidj"},
    {"debug.lib","mks"},
    {"disk","jesup"},
    {"diskfont","darren havemose kodiak davidj"},
    {"disk.resource","jesup"},
    {"documentation","dan izzy ross"},
    {"dos.command","jesup vertex"},
    {"dos.library","jesup"},
    {"exec","mks"},
    {"expansion","mks"},
    {"extras","eric"},
    {"filesysres","steveb jesup darren"},
    {"filesystem","steveb jesup"},
    {"fed","steveb"},
    {"fonts","eric darren"},
    {"fountain","havemose kodiak davidj"},
    {"gadget.classes","davidj vertex"},
    {"gadtools","peter vertex"},
    {"gameport","darren"},
    {"genlock","hedley"},
    {"graphics","spence chrisg steveb bart havemose"},
    {"handler","jesup"},
    {"hardware","grr"},
    {"hdbackup","eric"},
    {"hdtoolbox","jesup kaori"},
    {"icon.library","mks"},
    {"iconedit","davidj"},
    {"ide.device","jesup"},
    {"iffparse","eric carolyn rutgers!ucbvax!well!ewhac"},
    {"iprefs","vertex"},
    {"includes","peter eric"},
    {"input.device","darren"},
    {"installer","vertex larry"},
    {"intuition","peter darren"},
    {"kickstart","peter"},
    {"keyboard","darren"},
    {"keymap","darren"},
    {"keymaps","eric"},
    {"layers","spence chrisg mks bart"},
    {"locale.library","vertex"},
    {"mathf