#!/bin/sh
myargs=""
myfiles=""

# TMAC="/cats/public/tmac/tmac.ken"
# TMAC="/cats/public/tmac/tmac.aw"
TMAC="/cats/public/tmac/tmac.dan"

while ( test $# -ne 0 )
	do
	case $1 in
		-*) myargs="$myargs $1" ;;
		*)  myfiles="$myfiles $1" ;;
		esac
	shift
	done

# tbl $myfiles | eqn | nroff $myargs $TMAC - 2>/dev/null
tbl $myfiles |
	eqn |
	nroff $myargs $TMAC - 2>/dev/tty |
	sed -e 's/^          //g' |
	sed -e 's/^@@/\
/g' |
	cat -s

