##########################################################################
 
MAKEFILE=	Makefile
MAKEMETA=	/usr/commodore/amiga/V37/tools/makemeta

SUBDIRS=	16 9

all:            ${SUBDIRS}

.INCLUDE=${MAKEMETA}
