
/* Include file generated by Toolmaker V1.1.19 */

struct TMWindowInfo
  {
  struct Window *Window;
  struct Menu *Menu;
  struct Requester Requester;
  UBYTE DisableCount;
  ULONG Flags;
  struct Gadget **FirstGadget;
  APTR UserData;
  };

struct TMData
  {
  ULONG Size;
  struct MsgPort *WindowMsgPort;
  LONG ReturnCode;
  struct Screen     *Screen;
  struct VisualInfo *VisualInfo;
  struct Gadget *Window0Gadget[12];
  struct TMWindowInfo TMWindowInfo[1];
  APTR UserData;
  };

LONG TM_Request(struct Window *, char *, char *, char *);
LONG TM_Open(struct TMData **);
VOID TM_Close(struct TMData *);
VOID TM_EventLoop(struct TMData *);
VOID TM_RemoveWindow(struct TMWindowInfo *);
BOOL TM_WindowSignal(struct TMData *);
BOOL TM_Window0(struct TMData *, UBYTE);
BOOL TM_Window0IDCMP(struct TMData *, struct IntuiMessage *);
BOOL Window0GADGETDOWN(struct TMData *, struct IntuiMessage *);
BOOL Window0GADGETUP(struct TMData *, struct IntuiMessage *);
BOOL Window0CLOSEWINDOW(struct TMData *, struct IntuiMessage *);

extern struct Library *IntuitionBase, *GadToolsBase;
extern UWORD chip WaitPointer[];

#define DISPLAY  1
#define REMOVE   2
#define DISABLE  3
#define ENABLE   4

#define TMERROR_NONE       0
#define TMERROR_MEMORY     1
#define TMERROR_MSGPORT    2
#define TMERROR_SCREEN     3
#define TMERROR_VISUALINFO 4

#define TMWF_OPEN     0x00000001
#define TMWF_DISABLED 0x00000002

#define TITLEBARHEIGHT (TMData->Screen->BarHeight)

#define window_label1	TMData->TMWindowInfo[0].Window
#define gadget_label2	TMData->Window0Gadget[2]
#define gadget_label3	TMData->Window0Gadget[3]
#define gadget_label4	TMData->Window0Gadget[4]
#define gadget_label5	TMData->Window0Gadget[5]
#define gadget_label6	TMData->Window0Gadget[6]
#define gadget_label7	TMData->Window0Gadget[7]
#define gadget_label8	TMData->Window0Gadget[8]
#define gadget_label9	TMData->Window0Gadget[9]
#define gadget_label10	TMData->Window0Gadget[10]
#define gadget_label11	TMData->Window0Gadget[11]

#define ID_label2	1
#define ID_label3	2
#define ID_label4	3
#define ID_label5	4
#define ID_label6	5
#define ID_label7	6
#define ID_label8	7
#define ID_label9	8
#define ID_label10	9
#define ID_label11	10


#define Window_label1	TM_Window0
#define Window_label1_GADGETDOWN	Window0GADGETDOWN
#define Window_label1_GADGETUP	Window0GADGETUP
#define Window_label1_CLOSEWINDOW	Window0CLOSEWINDOW

#define WindowInfo_label1	TMData->TMWindowInfo[0]

