
/* Include file generated by Toolmaker V1.1.19 */

#define TEXT_W0TITLE	"New window"
#define TEXT_W0G2	"Cancel"
#define TEXT_W0G3	"Save"
#define TEXT_W0G4	"Delete"
#define TEXT_W0G5	"Add"
#define TEXT_W0G6	"Delete"
#define TEXT_W0G7	"Add"
#define TEXT_W0G8	"Users and Groups"
#define TEXT_W0G9	"Allow left-out icons"
#define TEXT_W0G10	"Allow volume snapshotting"
#define TEXT_W0G11	"Shared Directories"

