
#define WBPATTERN_PREFS
#define MSG_PREFS_NAME MSG_WBP_NAME
#define	MSG_OPEN_CLIP  MSG_WBP_OPEN_CLIPBOARD_STAT
#define	MSG_NO_GRAPHIC MSG_WBP_PASTE_GRAPHIC_STAT
#define MSG_REQ_LOAD   MSG_WBP_REQ_LOAD
#define MSG_REQ_SAVE   MSG_WBP_REQ_SAVE
