
/* Include file generated by Toolmaker V1.1.19 */

/* TMWindowInfo structure */

struct TMWindowInfo
  {
  struct Window *Window;	/* pointer to Window structure */
  struct Menu *Menu;	/* pointer to Menu structure */
  struct Requester Requester;	/* Requester structure for DISABLE/ENABLE */
  UBYTE DisableCount;	/* Count for nested DISABLE/ENABLEs */
  ULONG Flags;	/* TMWF_ flags */
  struct Gadget **FirstGadget;	/* pointer to gadget array */
  APTR UserData;
  };

/* TMData structure */

struct TMData
  {
  ULONG Size;	/* Size of TMData structure */
  struct MsgPort *WindowMsgPort;	/* pointer to window message port */
  ULONG UserSignal;	/* User signal flag for Wait */
  LONG ReturnCode;	/* Return code for exit() */
  struct Screen     *Screen;	/* pointer to Screen structure */
  struct VisualInfo *VisualInfo;	/* pointer to VisualInfo structure */
  struct Gadget *Window0Gadget[11];	/* Gadget structure array */
  struct TMWindowInfo TMWindowInfo[1];	/* TMWindowInfo structure array */
  APTR UserData;
  };

/* Function Prototypes */

LONG TM_Request(struct Window *, char *, char *, char *);
LONG TM_Open(struct TMData **);
VOID TM_Close(struct TMData *);
VOID TM_EventLoop(struct TMData *);
VOID TM_RemoveWindow(struct TMWindowInfo *);
BOOL TM_WindowSignal(struct TMData *);
BOOL UserSignal(struct TMData *, ULONG);
BOOL TM_Window0(struct TMData *, UBYTE);
BOOL TM_Window0IDCMP(struct TMData *, struct IntuiMessage *);
BOOL Window0GADGETDOWN(struct TMData *, struct IntuiMessage *);
BOOL Window0GADGETUP(struct TMData *, struct IntuiMessage *);
BOOL Window0CLOSEWINDOW(struct TMData *, struct IntuiMessage *);

/* Global Data */

extern struct Library *SysBase, *IntuitionBase, *GadToolsBase;
extern UWORD chip WaitPointer[];

/* General constants */

#define DISPLAY  1	/* Window function argument */
#define REMOVE   2	/* Window function argument */
#define DISABLE  3	/* Window function argument */
#define ENABLE   4	/* Window function argument */

#define TMERROR_NONE       0	/* Success */
#define TMERROR_MEMORY     1	/* AllocMem error */
#define TMERROR_MSGPORT    2	/* CreateMsgPort error */
#define TMERROR_SCREEN     3	/* OpenScreen/LockPubScreen error */
#define TMERROR_VISUALINFO 4	/* GetVisualInfo error */

#define TMWF_OPEN     0x00000001	/* Window control */
#define TMWF_DISABLED 0x00000002	/* Window disabled */

#define TITLEBARHEIGHT (TMData->Screen->BarHeight)	/* Height of title bar */

/* Window, Menu, and Gadget pointers */

#define window_LC_Window	TMData->TMWindowInfo[0].Window	/* Window pointer */
#define gadget_LC_Text0	TMData->Window0Gadget[2]	/* Gadget pointer */
#define gadget_LC_Send	TMData->Window0Gadget[3]	/* Gadget pointer */
#define gadget_LC_Timeout	TMData->Window0Gadget[4]	/* Gadget pointer */
#define gadget_LC_Class	TMData->Window0Gadget[5]	/* Gadget pointer */
#define gadget_LC_Entity	TMData->Window0Gadget[6]	/* Gadget pointer */
#define gadget_LC_Service	TMData->Window0Gadget[7]	/* Gadget pointer */
#define gadget_LC_Host	TMData->Window0Gadget[8]	/* Gadget pointer */
#define gadget_LC_Realm	TMData->Window0Gadget[9]	/* Gadget pointer */
#define gadget_LC_Result	TMData->Window0Gadget[10]	/* Gadget pointer */

/* Gadget IDs */

#define ID_LC_Text0	1	/* Gadget ID */
#define ID_LC_Send	2	/* Gadget ID */
#define ID_LC_Timeout	3	/* Gadget ID */
#define ID_LC_Class	4	/* Gadget ID */
#define ID_LC_Entity	5	/* Gadget ID */
#define ID_LC_Service	6	/* Gadget ID */
#define ID_LC_Host	7	/* Gadget ID */
#define ID_LC_Realm	8	/* Gadget ID */
#define ID_LC_Result	9	/* Gadget ID */

/* Menu, item, and subitem numbers */


/* Functions */

#define Window_LC_Window	TM_Window0	/* Window function */
#define Window_LC_Window_GADGETDOWN	Window0GADGETDOWN	/* GADGETDOWN IDCMP function */
#define Window_LC_Window_GADGETUP	Window0GADGETUP	/* GADGETUP IDCMP function */
#define Window_LC_Window_CLOSEWINDOW	Window0CLOSEWINDOW	/* CLOSEWINDOW IDCMP function */

/* WindowInfo pointers */

#define WindowInfo_LC_Window	TMData->TMWindowInfo[0]	/* WindowInfo structure pointer */

