
/* Include file generated by Toolmaker V1.1.19 */

/* Text */
 
#define TEXT_W0TITLE	"NIPC Locator Utility"
#define TEXT_W0G2	"Query Setup"
#define TEXT_W0G3	"Send Query"
#define TEXT_W0G4	"Timeout"
#define TEXT_W0G5	"Query Class"
#define TEXT_W0G5L1S1	"NHClass_Hosts"
#define TEXT_W0G5L1S2	"NHClass_Services"
#define TEXT_W0G5L1S3	"NHClass_Entities"
#define TEXT_W0G5L1S4	"NHClass_Realms"
#define TEXT_W0G6	"Entity Name"
#define TEXT_W0G7	"Service Name"
#define TEXT_W0G8	"Amiga Name"
#define TEXT_W0G9	"Realm Name"
#define TEXT_W0G10	"Query Result"

