*** This file generated on Tue Sep  9 11:39:37 1986
*** $Id: mathieeedoubtrans_lib.i,v 37.1 91/01/21 15:20:45 mks Exp $
	FUNCDEF	IEEEDPAtan
	FUNCDEF	IEEEDPSin
	FUNCDEF	IEEEDPCos
	FUNCDEF	IEEEDPTan
	FUNCDEF	IEEEDPSincos
	FUNCDEF	IEEEDPSinh
	FUNCDEF	IEEEDPCosh
	FUNCDEF	IEEEDPTanh
	FUNCDEF	IEEEDPExp
	FUNCDEF	IEEEDPLog
	FUNCDEF	IEEEDPPow
	FUNCDEF	IEEEDPSqrt
	FUNCDEF	IEEEDPTieee
	FUNCDEF	IEEEDPFieee
	FUNCDEF	IEEEDPAsin
	FUNCDEF	IEEEDPAcos
	FUNCDEF	IEEEDPLog10
