##########################################################################
 
MAKEFILE=	Makefile
MAKEMETA=	/usr/commodore/amiga/V37/tools/makemeta

SUBDIRS=	12 20

all:            ${SUBDIRS}

.INCLUDE=${MAKEMETA}
