;******************************************************************************
;
; pc_at.inc contains equals, which are different for  
;	    the PC- or AT-type of the A2000 emulator
;
;******************************************************************************
;
;--- Segment addresses -----------------
;
;ja_seg	       =    0f000h		; fixed seg of PC janus parameter area
;jb_seg	       =    0e000h		; fixed seg of PC janus buffer area
;
ja_seg	       =    0d000h		; fixed seg of AT janus parameter area
jb_seg	       =    0d400h		; fixed seg of AT janus buffer area
;


