€ƒtm
{
‚tm_sec,tm_min,tm_hour,
tm_mday,tm_mon,tm_year,
tm_wday,tm_yday,tm_isdst;
};ˆª
‹utunpk(,„*);
utpack(„*);
‹tzset(‹);
‚timer(‚*);
„*asctime(ƒtm*);
„*ctime(*);
ƒtm*gmtime(*);
ƒtm*localtime(*);
time(*);
‹utunpk();
utpack();
‹tzset();
„*asctime();
‚timer();
„*ctime();
ƒtm*gmtime();
ƒtm*localtime();
time();‡
¥time_t;
‚daylight;
timezone;
„*tzname[2];
„tzstn[4];
„tzdtn[4];€TZ "CST6"€YEAR0 1978€DAY0 0