/* gadgetids.h */

enum
{
	NOVAL,
	FSTYPE,		/* 39.13 */
	FFSCHK,		/* 39.13 */
	INTLMODE,	/* 39.13 */
	DIRCACHE,	/* 39.13 */
	FSBLOCKSIZE,	/* 39.13 */
	MASK,
	BUFMEMTYPE,
	BUFFERS,
	PRIORITY,
	RESERVEDEND,
	RESERVEDBEGIN,
	FSIDENTIFIER,
	FILESYSNAME,
	MAXTRANSFER,
	FSCANCEL,
	FSOK,
	DEFINEDRIVE,
	MODIFYDRIVE,
	TYPELIST,
	PARKWHERE,
	PARKHEAD,
	DRIVELIST,
	SIZEPART,
	CHANGEFILESYS,
	NAMEPART,
	HELP,
	DRAGPART,
	CANCELPART,
	DONEPART,
	HOSTID,
	BOOTPRI,
	BOOTABLE,
	AUTOMOUNT,
	TOTALCYL,
	ENDCYL,
	STARTCYL,
	UNDOLAST,
	DELETEPART,
	NEWPART,
	EXITPREP,
	PARTITIONDRIVE,
	FORMATDRIVE,
	LOWFORMAT,
	SURFCHECK,
	ADDFILESYS,
	FSMUPDATE,
	FSMDELETE,
	FSMADD,
	FSMCANCEL,
	FSMOK,
	FSMLIST,
	NDBLOCKS,
	NDCYLBLOCKS,
	NDHEADS,
	NDCYLINDERS,
	NDREADPARMS,
	NDPARKHEAD,
	NDPARKWHERE,
	NDPARKSECONDS,
	NDNORMAL,
	NDOMTI,
	NDADAPTEC,
	NDNORMALST506,
	NDNAME,
	NDMANUNAME,
	NDDRIVENAME,
	NDREVISIONNAME,
	NDREDUCED,
	NDPRECOMP,
	NDRESELECT,
	NDSYNCHRONOUS,
	NDCANCEL,
	NDOK,
	NOLLFORMAT,
	LLCANCEL,
	LLFORMAT,
	COMMITCANCEL,
	COMMITCONTINUE,
	FSGETNAMEOK,
	FSGETNAMECANCEL,
	FSGETTYPEOK,		// 39.9
	FSGETTYPECANCEL,	// 39.9
	GETFILENAME,
	GETDOSTYPE,
	GETVERSION,
	GETREVSION,		// 39.9
	BADOK,
	BADCANCEL,
	BADDELETE,
	BADADD,
	BADLIST,
	BADGETCANCEL,
	BADGETOK,
	BADBFI,
	BADHEAD,
	BADCYLINDER,
	BADBLOCK,
	EDITTYPE,
	DELETETYPE,
	SCSITYPE,
	USETYPE,
	HELPPREP,
	QUICKSETUP,
	INTERLEAVE,
	INTERLEAVEOK,
	INTERLEAVECANCEL,
	SETTYPEOK,
	SETTYPECANCEL,
	SETTYPE,
	ADVANCED,
	BADSEC,
	MAPSTOP,
	CUSTOMBOOT,
	CUSTOMNUM,
};

enum
{
	STANDARD_CYCLE,		/* current is standard FS */
	CUSTOM_CYCLE,		/* current is custom FS	  */
};

enum
{
	FSBS_512_CYCLE,		/* file system block size 512   */
	FSBS_1024_CYCLE,	/* file system block size 1024  */
	FSBS_2048_CYCLE,	/* file system block size 2048  */
	FSBS_4096_CYCLE,	/* file system block size 4096  */
	FSBS_8192_CYCLE,	/* file system block size 8192  */
	FSBS_16384_CYCLE,	/* file system block size 16384 */
	FSBS_32768_CYCLE,	/* file system block size 32768 */
};

