##########################################################################

MAKEFILE=	Makefile
MAKEMETA=	/usr/commodore/amiga/V37/tools/makemeta
SRCDIRPATH=	workbench/fonts/courier
SRCDIR=		24
SUBSYSNAME=	24
DISKPATH=	fonts/courier/24

AFILES=		24.asm
OFILES=		24.obj

all:		${SUBSYSNAME}.ld

.INCLUDE=${MAKEMETA}
SYMBOLOPT=
