mkdir a
mkdir a/b
mkdir a/b/c
mkdir a/b/c/d
mkdir a/b/c/d/e
mkdir a/b/c/d/e/f
mkdir a/b/c/d/e/f/g
mkdir a/b/c/d/e/f/g/h
mkdir a/b/c/d/e/f/g/h/i
mkdir a/b/c/d/e/f/g/h/i/j
mkdir a/b/c/d/e/f/g/h/i/j/k
mkdir a/b/c/d/e/f/g/h/i/j/k/l
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/a
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/a/b
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/a/b/c
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/a/b/c/d
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/a/b/c/d/e
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/a/b/c/d/e/f
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/a/b/c/d/e/f/g
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/a/b/c/d/e/f/g/h
mkdir a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/a/b/c/d/e/f/g/h/i
