echo >frwed "frwed"
filenote frwed comment frwed
protect frwed rwed
echo >frwe "frwe"
filenote frwe comment frwe
protect frwe rwe
echo >frwd "frwd"
filenote frwd comment frwd
protect frwd rwd
echo >frw "frw"
filenote frw comment frw
protect frw rw
echo >fred "fred"
filenote fred comment fred
protect fred red
echo >fre "fre"
filenote fre comment fre
protect fre re
echo >frd "frd"
filenote frd comment frd
protect frd rd
echo >fr "fr"
filenote fr comment fr
protect fr r
echo >fwed "fwed"
filenote fwed comment fwed
protect fwed wed
echo >fwe "fwe"
filenote fwe comment fwe
protect fwe we
echo >fwd "fwd"
filenote fwd comment fwd
protect fwd wd
echo >fw "fw"
filenote fw comment fw
protect fw w
echo >fed "fed"
filenote fed comment fed
protect fed ed
echo >fe "fe"
filenote fe comment fe
protect fe e
echo >fd "fd"
filenote fd comment fd
protect fd d
echo >f "f"
filenote f comment f
protect f 
